---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords: Type of backups 
summary: '使用SnapCenter備份 SQL Server 系統和使用者資料庫需要您選擇資源類型，例如資料庫、SQL 伺服器執行個體和可用性群組 (AG)。利用快照技術來建立資源所在磁碟區的線上、唯讀副本。' 
---
= 支援的備份類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用SnapCenter備份 SQL Server 系統和使用者資料庫需要您選擇資源類型，例如資料庫、SQL 伺服器執行個體和可用性群組 (AG)。利用快照技術來建立資源所在磁碟區的線上、唯讀副本。

您可以選擇僅複製選項來指定 SQL Server 不截斷交易日誌。當您使用其他備份應用程式管理 SQL Server 時，應使用此選項。保持交易日誌完整可使任何備份應用程式還原系統資料庫。僅複製備份與排程備份的順序無關，且不會影響資料庫的備份和還原過程。

|===
| 備份類型 | 描述 | 具有備份類型的僅複製選項 


 a| 
完整備份和日誌備份
 a| 
備份系統資料庫並截斷交易日誌。

SQL Server 透過刪除已提交至資料庫的項目來截斷交易日誌。

完整備份完成後，此選項會建立一個擷取交易資訊的交易日誌。通常，您應該選擇此選項。但是，如果您的備份時間很短，您可以選擇不執行交易日誌備份，而是進行完整備份。

您不能為 master 和 msdb 系統資料庫建立日誌備份。但是，您可以為模型系統資料庫建立日誌備份。
 a| 
備份系統資料庫檔案和交易日誌而不截斷日誌。

僅複製備份不能作為差異基準或差異備份，且不會影響差異基準。恢復僅複製完整備份與恢復任何其他完整備份相同。



 a| 
完整資料庫備份
 a| 
備份系統資料庫檔案。

您可以為主資料庫、模型資料庫和 msdb 系統資料庫建立完整的資料庫備份。
 a| 
備份系統資料庫檔案。



 a| 
交易日誌備份
 a| 
備份截斷的交易日誌，僅複製自最近的交易日誌備份以來提交的交易。

如果您安排頻繁的交易日誌備份和完整的資料庫備份，則可以選擇粒度復原點。
 a| 
備份交易日誌而不截斷它們。

此備份類型不會影響常規日誌備份的順序。僅複製日誌備份對於執行線上復原作業很有用。

|===