---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter使用憑證對SnapCenter操作的使用者進行身份驗證。您應該建立用於安裝SnapCenter插件的憑證以及用於在資料庫或 Windows 檔案系統上執行資料保護作業的附加憑證。 
---
= 為 Windows 的SnapCenter插件包設定憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter使用憑證對SnapCenter操作的使用者進行身份驗證。您應該建立用於安裝SnapCenter插件的憑證以及用於在資料庫或 Windows 檔案系統上執行資料保護作業的附加憑證。

.開始之前
* 在安裝插件之前，您必須設定 Windows 憑證。
* 您必須設定具有管理員權限的憑證，包括遠端主機上的管理員權限。
* Windows 主機上的 SQL 驗證
+
安裝插件後，您必須設定 SQL 憑證。

+
如果您正在為 Microsoft SQL Server 部署SnapCenter插件，則必須在安裝插件後設定 SQL 憑證。為具有 SQL Server sysadmin 權限的使用者設定憑證。

+
SQL 驗證方法針對 SQL Server 執行個體進行驗證。這意味著必須在SnapCenter中發現 SQL Server 執行個體。因此，在新增SQL憑證前，必須先新增主機、安裝外掛程式包、刷新資源。您需要 SQL Server 驗證才能執行諸如調度或發現資源之類的操作。



.步驟
. 在左側導覽窗格中，按一下「*設定*」。
. 在「設定」頁面中，按一下「*憑證*」。
. 點選“*新建*”。
. 在「憑證」頁面中，指定配置憑證所需的資訊：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
憑證名稱
 a| 
輸入憑證的名稱。



 a| 
使用者名稱/密碼
 a| 
輸入用於身份驗證的使用者名稱和密碼。

** 網域管理員
+
指定要安裝SnapCenter插件的系統上的網域管理員。用戶名字段的有效格式為：

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** 本機管理員（僅適用於工作群組）
+
對於屬於工作群組的系統，請在要安裝SnapCenter插件的系統上指定內建的本機管理員。如果使用者帳戶具有提升的權限或主機系統上停用了使用者存取控制功能，則可以指定屬於本機管理員群組的本機使用者帳戶。用戶名字段的有效格式為： `UserName`

+
請勿在密碼中使用雙引號（“）或反引號（`）。密碼中不應同時使用小於號 (<) 和驚嘆號 (!) 符號。例如，lessthan<!10、lessthan10<!、backtick`12。





 a| 
認證模式
 a| 
選擇您想要使用的身份驗證模式。如果選擇SQL驗證模式，也必須指定SQL伺服器執行個體以及SQL實例所在的主機。

|===
. 按一下“*確定*”。


完成憑證設定後，您可能想要在「使用者和造訪」頁面中將憑證維護指派給使用者或使用者群組。
