---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: 您可以在使用SnapCenter備份 SQL Server 資源之前為資源或資源群組建立備份策略，也可以在建立資源群組或備份單一資源時建立備份原則。 
---
= 為 SQL Server 資料庫建立備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在使用SnapCenter備份 SQL Server 資源之前為資源或資源群組建立備份策略，也可以在建立資源群組或備份單一資源時建立備份原則。

.開始之前
* 您必須已經定義了您的資料保護策略。
* 您必須透過完成安裝SnapCenter、新增主機、識別資源和建立儲存系統連線等任務來為資料保護做好準備。
* 您必須已設定主機日誌目錄以進行日誌備份。
* 您必須刷新（發現）SQL Server 資源。
* 如果您要將快照複製到映像或保管庫， SnapCenter管理員必須已為您指派來源磁碟區和目標磁碟區的儲存虛擬機器 (SVM)。
+
有關管理員如何向使用者指派資源的信息，請參閱SnapCenter安裝資訊。

* 如果您想要在前腳本和後腳本中執行 PowerShell 腳本，則應在 web.config 檔案中將 usePowershellProcessforScripts 參數的值設為 true。
+
預設值為 false。

* 查看SnapMirror主動同步特定的先決條件和限制。欲了解詳細信息，請參閱 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror主動同步的物件限制"]。


.關於此任務
* 備份策略是一組規則，用於控制如何管理和保留備份以及資源或資源群組的備份頻率。此外，您還可以指定複製和腳本設定。當您想要將策略重新用於另一個資源群組時，在策略中指定選項可以節省時間。
+
SCRIPTS_PATH 是使用插件主機的 SMCoreServiceHost.exe.Config 檔案中的 PredefinedWindowsScriptsDirectory 鍵定義的。

+
如果需要，您可以變更此路徑並重新啟動 SMcore 服務。為了安全起見，建議您使用預設路徑。

+
可以透過 API 從 Swagger 顯示該鍵的值：API /4.7/configsettings

+
您可以使用 GET API 來顯示鍵的值。不支援 SET API。

* SnapLock
+
** 如果選擇了「保留備份副本特定天數」選項，則SnapLock保留期必須小於或等於上述保留天數。
+
指定快照鎖定期可防止在保留期到期之前刪除快照。這可能導致保留的快照數量超過策略中指定的數量。

+
對於ONTAP 9.12.1 及以下版本、作為復原的一部分從SnapLock Vault 快照建立的克隆將繼承SnapLock Vault 到期時間。儲存管理員應在SnapLock到期後手動清理克隆。







== 步驟 1：建立策略名稱

. 在左側導覽窗格中，選擇「*設定*」。
. 在設定頁面中，選擇*策略*。
. 選擇“*新建*”。
. 在*名稱*頁面中，輸入策略名稱和詳細資訊。




== 步驟 2：設定策略選項

. 在「策略類型」頁面中，執行下列步驟：
+
.. 選擇您的儲存類型。
.. 選擇您的保單範圍。
+
[role="tabbed-block"]
====
.完整備份和日誌備份
--
備份資料庫檔案和交易日誌並截斷交易日誌。

... 選擇*完整備份和日誌備份*。
... 輸入每個快照應備份的最大資料庫數量。
+

NOTE: 如果要同時執行多個備份操作，則必須增加此值。



--
.完整備份
--
備份資料庫檔案。

... 選擇*完整備份*。
... 輸入每個快照應備份的資料庫的最大數量。預設值為 100
+

NOTE: 如果要同時執行多個備份操作，則必須增加此值。



--
.日誌備份
--
... 備份交易日誌。
... 選擇*日誌備份*。


--
.僅複製備份
--
... 如果您使用其他備份應用程式備份資源，請選擇*僅複製備份*。


保持交易日誌完整允許任何備份應用程式還原資料庫。通常，您不應在任何其他情況下使用僅複製選項。


NOTE: Microsoft SQL 不支援將「僅複製備份」選項與「完整備份和記錄備份」選項一起用於輔助儲存。

--
====






== 步驟 3：設定可用性群組設定

. 在可用性群組設定部分中，執行以下操作：
+
.. 僅在首選備份副本上備份。
+
選擇此選項僅在首選備份副本上備份。首選備份副本由 SQL Server 中為 AG 配置的備份首選項決定。

.. 選擇要備份的副本。
+
選擇主 AG 副本或輔助 AG 副本進行備份。

.. 選擇備份優先權（最小和最大備份優先權）
+
指定最小備份優先權數和最大備份優先權數，以決定要備份的 AG 副本。例如，最小優先權可以為 10，最大優先權可以為 50。在這種情況下，所有優先權大於 10 且小於 50 的 AG 副本都被視為備份。

+
預設情況下，最小優先權為 1，最大優先權為 100。



+

NOTE: 在叢集配置中，備份會根據策略中設定的保留設定保留在叢集的每個節點上。如果 AG 的擁有者節點發生變化，則根據保留設定進行備份，並且將保留前一個所有者節點的備份。  AG 的保留僅適用於節點層級。





== 步驟 4：設定快照和複製設定

. 在「快照和複製」頁面中，執行下列步驟：
+
.. 透過選擇*按需*、*每小時*、*每日*、*每週*或*每月*來指定方案類型。
+
一個策略只能選擇一種計劃類型。

+

NOTE: 您可以在建立資源組時指定備份作業的計畫（開始日期、結束日期和頻率）。這使您能夠建立共享相同策略和備份頻率的資源群組，但允許您為每個策略指派不同的備份計劃。

+

NOTE: 如果您已安排在凌晨 2:00，則夏令時 (DST) 期間不會觸發該計劃。







== 步驟 5：配置最新的保留設置

. 在「最新保留設定」部分中，根據備份類型頁面中所選的備份類型，執行下列操作中的一項或多項：


[role="tabbed-block"]
====
.具體份數
--
僅保留特定數量的快照。

. 選擇*保留適用於最近<number>天的日誌備份*選項，並指定要保留的天數。如果接近此限制，您可能需要刪除舊副本。


--
.具體天數
--
將備份副本保留特定天數。

. 選擇*保留適用於最後<number>天完整備份的日誌備份*選項，並指定保留日誌備份副本的天數。


--
====


== 步驟 6：配置快照設定

. 對於完整備份保留設置，請執行以下操作：
+
.. 指定要保留的快照總數
+
... 若要指定要保留的快照數量，請選擇*要保留的副本*。
... 如果快照數量超過指定數量，則會刪除快照，並先刪除最舊的副本。
+

IMPORTANT: 預設情況下，保留計數的值設定為 2。如果將保留計數設為 1，則保留操作可能會失敗，因為第一個快照是SnapVault關係的參考快照，直到較新的快照複製到目標。

+

NOTE: 最大保留值為 1018。如果保留設定的值高於底層NetApp ONTAP版本支援的值，則備份將會失敗。







. 保留快照的時間長度
+
.. 如果您想要指定在刪除快照之前保留快照的天數，請選擇「保留副本」****。


. 選擇*Snapshot 副本鎖定期限*並指定天、月或年的持續時間。
+
Snaplock 保留期應少於 100 年。

. 選擇一個策略標籤。
+

NOTE: 您可以為遠端複製的主快照指派SnapMirror標籤，從而允許主快照將快照複製作業從SnapCenter卸載到ONTAP二級系統。無需在策略頁面中啟用SnapMirror或SnapVault選項即可完成此操作。





== 步驟 7：配置輔助複製選項

. 在「選擇輔助複製選項」部分中，選擇以下一個或兩個輔助複製選項：


[role="tabbed-block"]
====
.更新SnapMirror
--
建立本機 Snapshot 副本後更新SnapMirror 。

. 選擇此選項可在另一個磁碟區上建立備份集的鏡像副本（SnapMirror）。
+
應為SnapMirror主動同步啟用此選項。

+
在二次複製期間， SnapLock到期時間會載入主SnapLock到期時間。點選拓樸頁面中的「*刷新*」按鈕可重新整理從ONTAP擷取的輔助和主SnapLock到期時間。

+
看link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["在拓樸頁面中檢視 SQL Server 備份和克隆"] 。



--
.更新SnapVault
--
建立 Snapshot 副本後更新SnapVault 。

. 選擇此選項可執行磁碟到磁碟的備份複製。
+
在二次複製期間， SnapLock到期時間會載入主SnapLock到期時間。點選拓樸頁面中的「*刷新*」按鈕可重新整理從ONTAP擷取的輔助和主SnapLock到期時間。

+
當僅在ONTAP的輔助節點（稱為SnapLock Vault）上配置SnapLock時，點擊拓撲頁面中的 *刷新* 按鈕將刷新從ONTAP檢索到的輔助節點上的鎖定期。

+
有關SnapLock Vault 的更多信息，請參閱 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["將 Snapshot 副本提交到保管庫目標上的 WORM"]

+
看link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["在拓樸頁面中檢視 SQL Server 備份和克隆"] 。



--
.錯誤重試次數
--
. 輸入進程停止之前應發生的複製嘗試次數。


--
====


== 步驟 8：配置腳本設定

. 在腳本頁面中，分別輸入應在備份作業之前或之後執行的前置腳本或後置腳本的路徑和參數。
+
例如，您可以執行腳本來更新 SNMP 陷阱、自動發出警報和傳送日誌。

+

NOTE: 前言或後記路徑不應包含磁碟機或共用。該路徑應相對於 SCRIPTS_PATH。

+

NOTE: 您必須在ONTAP中設定SnapMirror保留策略，以便二級儲存不會達到快照的最大限制。





== 步驟 9：配置驗證設定

在驗證頁面中，執行以下步驟：

. 在「執行以下備份計畫的驗證」部分中，選擇計畫頻率。
. 在資料庫一致性檢查選項部分中，執行下列操作：
+
.. 將完整性結構限制為資料庫的物理結構（PHYSICAL_ONLY）
+
... 選擇*將完整性結構限制為資料庫的實體結構（PHYSICAL_ONLY）*以將完整性檢查限制為資料庫的實體結構，並偵測影響資料庫的頁面撕裂、校驗和失敗以及常見硬體故障。


.. 抑制所有資訊訊息（NO INFOMSGS）
+
... 選擇*抑制所有訊息訊息（NO_INFOMSGS）*以抑制所有訊息訊息。預設選擇。


.. 顯示每個物件報告的所有錯誤訊息（ALL_ERRORMSGS）
+
... 選擇*顯示每個物件報告的所有錯誤訊息（ALL_ERRORMSGS）*以顯示每個物件報告的所有錯誤。


.. 不檢查非聚集索引（NOINDEX）
+
... 如果不想檢查非聚集索引，請選擇「不檢查非聚集索引 (NOINDEX)」。  SQL Server 資料庫使用 Microsoft SQL Server 資料庫一致性檢查器 (DBCC) 來檢查資料庫中物件的邏輯和實體完整性。


.. 限制檢查並取得鎖，而不是使用內部資料庫快照（TABLOCK）
+
... 選擇*限制檢查並取得鎖定而不是使用內部資料庫快照副本（TABLOCK）*來限制檢查並取得鎖定而不是使用內部資料庫快照。




. 在*日誌備份*部分中，選擇*完成後驗證日誌備份*以在完成後驗證日誌備份。
. 在*驗證腳本設定*部分中，分別輸入在驗證操作之前或之後應執行的腳本或後腳本的路徑和參數。
+

NOTE: 前言或後記路徑不應包含磁碟機或共用。該路徑應相對於 SCRIPTS_PATH。





== 步驟 10：審核摘要

. 查看摘要，然後選擇*完成*。

