---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: 使用SnapCenter，您可以從資源組或資料庫建立克隆。您可以執行按需克隆，也可以安排資源群組或資料庫的重複克隆操作。如果您定期複製備份，則可以使用該複製來開發應用程式、填充資料或還原資料。 
---
= 執行複製生命週期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用SnapCenter，您可以從資源組或資料庫建立克隆。您可以執行按需克隆，也可以安排資源群組或資料庫的重複克隆操作。如果您定期複製備份，則可以使用該複製來開發應用程式、填充資料或還原資料。

SnapCenter可讓您安排多個複製作業在多個伺服器上同時執行。

.開始之前
* 複製到獨立資料庫執行個體時，請確保掛載點路徑存在且是專用磁碟。
* 當複製到故障轉移群集實例 (FCI) 時，請確保掛載點存在、它是共用磁碟，且路徑和 FCI 應該屬於同一個 SQL 資源組。
* 如果來源資料庫或目標執行個體位於叢集共用磁碟區（csv）上，則複製的資料庫將位於 csv 上。



NOTE: 對於虛擬環境（VMDK/RDM），請確保掛載點是專用磁碟。

.關於此任務
* SCRIPTS_PATH 是使用插件主機的 SMCoreServiceHost.exe.Config 檔案中的 PredefinedWindowsScriptsDirectory 鍵定義的。
+
如果需要，您可以變更此路徑並重新啟動 SMcore 服務。為了安全起見，建議您使用預設路徑。

+
可以透過 API 從 Swagger 顯示該鍵的值：API /4.7/configsettings

+
您可以使用 GET API 來顯示鍵的值。不支援 SET API。

* 複製生命週期精靈頁面上的大多數欄位都是不言自明的。以下資訊描述了您可能需要指導的欄位。
* 對於ONTAP 9.12.1 及以下版本，如果指定 Snapshot 鎖定期限，則從防篡改快照創建的克隆將繼承SnapLock到期時間。儲存管理員應在SnapLock到期後手動清理克隆。


.步驟
. 在左側導覽窗格中，按一下“*資源*”，然後從清單中選擇適當的外掛程式。
. 在資源頁面中，從*視圖*清單中選擇*資料庫*或*資源組*。
. 選擇資源群組或資料庫，然後按一下「克隆生命週期」。
. 在「選項」頁面中，執行以下操作：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
克隆作業名稱
 a| 
指定複製生命週期作業名稱，以協助監控和修改複製生命週期作業。



 a| 
克隆伺服器
 a| 
選擇要放置克隆的主機。



 a| 
克隆實例
 a| 
選擇要將資料庫克隆到的克隆實例。此 SQL 實例必須位於指定的克隆伺服器中。



 a| 
克隆後綴
 a| 
輸入將附加到克隆資料庫的後綴，以標識它是一個克隆。用於建立克隆資源組的每個 SQL 實例都必須具有唯一的資料庫名稱。例如，如果克隆資源組包含來自 SQL 實例“inst1”的來源資料庫“db1”，並且如果“db1”被複製到“inst1”，則克隆資料庫名稱應該是“db1__clone”。 “`__clone`” 是強制的使用者定義後綴，因為資料庫被複製到同一個實例。如果將“`db1`”複製到 SQL 執行個體“`inst2`”，則複製資料庫名稱可以保留為“`db1`”（後綴是可選的），因為資料庫被複製到不同的執行個體。



 a| 
自動分配掛載點或自動分配路徑下的磁碟區掛載點
 a| 
選擇是否自動分配路徑下的掛載點或磁碟區掛載點。選擇自動分配路徑下的磁碟區掛載點可讓您提供特定的目錄。掛載點將在該目錄內建立。在選擇此選項之前，您必須確保目錄為空。如果目錄中存在資料庫，則掛載操作後資料庫將處於無效狀態。

|===
. 在位置頁面中，選擇用於建立複製的儲存位置。
. 在腳本頁面中，分別輸入複製操作之前或之後應執行的前置腳本或後置腳本的路徑和參數。
+
例如，您可以執行腳本來更新 SNMP 陷阱、自動發出警報、傳送日誌等。

+

NOTE: 前言或後記路徑不應包含磁碟機或共用。該路徑應相對於 SCRIPTS_PATH。

+
預設腳本超時為 60 秒。

. 在「計劃」頁面中，執行下列其中一項操作：
+
** 如果您想立即執行複製作業，請選擇*立即執行*。
** 當您想要確定克隆操作發生的頻率、克隆計劃的開始時間、克隆操作發生的日期、計劃的到期時間以及計劃到期後是否必須刪除克隆時，請選擇*配置計劃*。


. 在通知頁面中，從*電子郵件首選項*下拉清單中，選擇您想要傳送電子郵件的場景。
+
您也必須指定寄件者和收件者的電子郵件地址以及電子郵件的主題。如果您想要附加執行的複製操作的報告，請選擇*附加作業報告*。

+

NOTE: 對於電子郵件通知，您必須使用 GUI 或 PowerShell 命令 Set-SmSmtpServer 指定 SMTP 伺服器詳細資訊。

+
對於 EMS，您可以參考 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection.html["管理 EMS 資料收集"]

. 查看摘要，然後按一下「*完成*」。


您應該使用*Monitor* > *Jobs*頁面來監控複製過程。
