---
permalink: protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html 
sidebar: sidebar 
keywords: storage types, iSCSI, NFS, RDM, VMDK, NFS, LVM, ASM, SAN filesystem 
summary: SnapCenter支援實體機器和虛擬機器上的多種儲存類型。在安裝適用於 Linux 的SnapCenter插件包或適用於 AIX 的SnapCenter插件包之前，您必須驗證對您的儲存類型的支援。 
---
= Oracle Database 外掛程式支援的儲存類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter支援實體機器和虛擬機器上的多種儲存類型。在安裝適用於 Linux 的SnapCenter插件包或適用於 AIX 的SnapCenter插件包之前，您必須驗證對您的儲存類型的支援。

SnapCenter不支援 Linux 和 AIX 的儲存配置。



== Linux 支援的儲存類型

下表列出了 Linux 上支援的儲存類型。

|===
| 機器 | 儲存類型 


 a| 
實體伺服器
 a| 
* FC 連接的 LUN
* iSCSI 連接的 LUN
* NFS 連結卷
* NVMe光纖通道
* NVMe/TCP




 a| 
VMware ESXi
 a| 
* 透過 FC 或 iSCSI ESXi HBA 連線的 RDM LUN 主機匯流排適配器 (HBA) 掃描可能需要很長時間才能完成，因為SnapCenter會掃描主機中存在的所有主機匯流排適配器。
+
您可以編輯位於 _/opt/ NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_ 的 *LinuxConfig.pm* 文件，將 *SCSI_HOSTS_OPTIMIZED_RESCAN* 參數的值設定為 1，以僅重新掃描 HBA_DRI VBA 中列出的那些參數的值。

* iSCSI LUN 由 iSCSI 啟動器直接連接到客戶系統
* NFS 資料儲存上的 VMDK
* 透過 NVMe/TCP 建立的 VMFS 上的 VMDK
+

NOTE: ESX 8.0U2 支援 RAC，並支援共享 VMDK

* NFS 磁碟區直接連接到客戶系統
* NFS 和 SAN 上的 vVol 資料存儲
+
vVol 資料儲存只能使用適用於 VMware vSphere 的ONTAP Tools 進行設定。



|===


== AIX 上支援的儲存類型

下表列出了 AIX 上支援的儲存類型。

|===
| 機器 | 儲存類型 


 a| 
實體伺服器
 a| 
* FC 連線和 iSCSI 連線的 LUN。
+
在 SAN 環境中，支援 ASM、LVM 和 SAN 檔案系統。

+

NOTE: 不支援 AIX 和檔案系統上的 NFS。

* 增強型日誌檔案系統 (JFS2)
+
支援 SAN 檔案系統和 LVM 佈局上的內聯日誌記錄。



|===
這 https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["NetApp互通性表工具"]包含受支援版本的最新資訊。
