---
permalink: protect-sco/task_define_a_restore_and_recovery_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, restore methods, connect-and-copy restore, full restore, partial restore, in-place restore, recovery type, limitations 
summary: 您必須在還原和復原資料庫之前定義一個策略，以便能夠成功執行還原和復原作業。 
---
= 定義 Oracle 資料庫的還原與復原策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須在還原和復原資料庫之前定義一個策略，以便能夠成功執行還原和復原作業。



== 還原和復原作業支援的備份類型

SnapCenter支援不同類型的 Oracle 資料庫備份的還原和還原。

* 線上資料備份
* 離線關機資料備份
* 離線掛載資料備份
+

NOTE: 如果您正在恢復離線關閉或離線掛載資料備份， SnapCenter會使資料庫處於離線狀態。您應該手動恢復資料庫並重置日誌。

* 完整備份
* Data Guard 備用資料庫的離線備份
* Active Data Guard 備用資料庫的僅資料線上備份
+

NOTE: 您無法執行 Active Data Guard 備用資料庫的復原。

* 真實應用叢集 (RAC) 設定中的線上資料備份、線上完整備份、離線掛載備份和離線關機備份
* 自動儲存管理 (ASM) 設定中的線上資料備份、線上完整備份、離線掛載備份和離線關機備份




== Oracle 資料庫支援的還原方法類型

SnapCenter支援 Oracle 資料庫的連線和複製或就地還原。在還原作業期間， SnapCenter會決定適合檔案系統的還原方法，以便用於還原而不會遺失任何資料。


NOTE: SnapCenter不支援基於磁碟區的SnapRestore。



=== 連線並複製恢復

如果資料庫佈局與備份不同，或在建立備份後有任何新文件，則執行連線和複製還原。在連線和複製還原方法中，執行下列任務：

*步驟*

. 該磁碟區是從快照克隆的，並且使用克隆的 LUN 或磁碟區在主機上建立檔案系統堆疊。
. 文件從克隆的檔案系統複製到原始檔案系統。
. 然後從主機上卸載克隆的檔案系統，並從ONTAP中刪除克隆的磁碟區。



NOTE: 對於 Flex ASM 設定（基數小於 RAC 叢集中的節點數）或 VMDK 或 RDM 上的 ASM RAC 資料庫，僅支援連接和複製復原方法。

即使您已強制啟用就地還原， SnapCenter也會在下列情況下執行連線和複製還原：

* 從輔助儲存系統復原
* 還原未配置資料庫實例的 Oracle RAC 設定節點上的 ASM 磁碟組
* 在 Oracle RAC 設定中，如果 ASM 實例或叢集實例未執行，或對等節點已關閉，則在任何對等節點上
* 僅恢復控製文件
* 復原位於 ASM 磁碟組上的表空間子集
* 資料檔案、sp檔案、密碼檔案共享磁碟組
* SnapCenter插件Loader(SPL) 服務未安裝或未在 RAC 環境中的遠端節點上執行
* 新節點已新增至 Oracle RAC，但SnapCenter伺服器不知道新新增的節點




=== 就地還原

如果資料庫佈局與備份類似，且在儲存體和資料庫堆疊上沒有發生任何設定更改，則執行就地還原，其中在ONTAP上執行檔案或 LUN 的還原。  SnapCenter僅支援單一檔案SnapRestore (SFSR) 作為就地復原方法的一部分。


NOTE: NetApp ONTAP支援從輔助位置進行就地復原。

如果要在資料庫上執行就地恢復，請確保 ASM 磁碟組上只有資料檔案。對 ASM 磁碟組或資料庫的實體結構進行任何變更後，都必須建立備份。執行就地復原後，磁碟組將包含與備份時相同數量的資料檔案。

當磁碟組或掛載點符合下列條件時，將自動套用就地還原：

* 備份後沒有新增新的資料檔案（外部檔案檢查）
* 備份後不新增、刪除或重新建立 ASM 磁碟或 LUN（ASM 磁碟組結構變化檢查）
* 不向 LVM 磁碟組新增、刪除或重新建立 LUN（LVM 磁碟組結構變化檢查）



NOTE: 您也可以使用 GUI、 SnapCenter CLI 或 PowerShell cmdlet 強制啟用就地還原，以覆寫外部檔案檢查和 LVM 磁碟組結構變更檢查。



==== 在 ASM RAC 上執行就地恢復

在SnapCenter中，執行還原的節點稱為主節點，而 ASM 磁碟組所在的 RAC 的所有其他節點稱為對等節點。在執行儲存還原作業之前， SnapCenter會在 ASM 磁碟組處於掛載狀態的所有節點上將 ASM 磁碟組的狀態變更為卸載。儲存恢復完成後， SnapCenter會將 ASM 磁碟組的狀態變更為復原作業之前的狀態。

在 SAN 環境中， SnapCenter會從所有對等節點中刪除設備，並在儲存復原作業之前執行 LUN 取消對映操作。儲存復原作業後， SnapCenter執行 LUN 對映操作並在所有對等節點上建置裝置。在 SAN 環境中，如果 Oracle RAC ASM 佈局駐留在 LUN 上，則在還原SnapCenter時，會在 ASM 磁碟組所在的 RAC 叢集的所有節點上執行 LUN 取消對應、LUN 還原和 LUN 對應操作。即使在還原之前 RAC 節點的所有啟動器都沒有用於 LUN，還原之後SnapCenter也會使用所有 RAC 節點的所有啟動器建立新的 iGroup。

* 如果對等節點上的預還原活動期間發生任何故障， SnapCenter會自動將 ASM 磁碟組狀態回滾到在預還原作業成功的對等節點上執行還原之前的狀態。主節點和操作失敗的對等節點不支援回滾。在嘗試另一次復原之前，您必須手動修復對等節點上的問題，並將主節點上的 ASM 磁碟組還原為安裝狀態。
* 如果在復原活動期間出現任何故障，則復原操作失敗且不會執行回溯。在嘗試另一次復原之前，您必須手動修復儲存復原問題並使主節點上的 ASM 磁碟組還原到安裝狀態。
* 如果任何對等節點上的復原後活動期間出現任何故障， SnapCenter將繼續在其他對等節點上執行復原作業。您必須手動修復對等節點上的復原後問題。




== Oracle 資料庫支援的還原作業類型

SnapCenter可讓您對 Oracle 資料庫執行不同類型的復原作業。

在還原資料庫之前，將驗證備份以確定與實際資料庫檔案相比是否缺少任何檔案。



=== 完全恢復

* 僅恢復資料檔案
* 僅恢復控製文件
* 恢復資料檔案和控製文件
* 還原 Data Guard 備用資料庫和 Active Data Guard 備用資料庫中的資料檔案、控製檔案和重做日誌文件




=== 部分恢復

* 僅恢復選定的表空間
* 僅恢復選定的可插拔資料庫 (PDB)
* 僅恢復 PDB 的選定表空間




== Oracle 資料庫支援的復原作業類型

SnapCenter可讓您對 Oracle 資料庫執行不同類型的復原作業。

* 資料庫直到最後事務（所有日誌）
* 資料庫達到特定的系統變更號碼（SCN）
* 資料庫直到特定的日期和時間
+
您必須根據資料庫主機的時區指定復原的日期和時間。

+
SnapCenter也為 Oracle 資料庫提供了無復原選項。




NOTE: 如果您使用以資料庫角色作為備用建立的備份進行恢復，則 Oracle 資料庫外掛程式不支援恢復。您必須始終對實體備用資料庫執行手動復原。



== 與 Oracle 資料庫還原和復原相關的限制

在執行還原和復原操作之前，您必須了解其限制。

如果您使用的是 Oracle 11.2.0.4 至 12.1.0.1 中的任何版本，則執行 _renamedg_ 指令時還原作業將處於暫停狀態。您可以套用 Oracle 補丁 19544733 來修復此問題。

不支援以下還原和復原操作：

* 根容器資料庫 (CDB) 表空間的還原和恢復
* 恢復臨時表空間和與 PDB 關聯的臨時表空間
* 同時從多個 PDB 還原和還原表空間
* 復原日誌備份
* 將備份還原到其他位置
* 在 Data Guard 備用資料庫或 Active Data Guard 備用資料庫以外的任何設定中還原重做記錄檔
* 恢復 SPFILE 和密碼文件
* 當您對使用相同主機上預先存在的資料庫名稱重新建立、由SnapCenter管理且具有有效備份的資料庫執行還原作業時，還原作業會覆寫新建立的資料庫文件，即使 DBID 不同。
+
可以透過執行以下操作之一來避免這種情況：

+
** 重新建立資料庫後發現SnapCenter資源
** 建立重新建立的資料庫的備份






== 與表空間的時間點恢復相關的限制

* 不支援 SYSTEM、SYSAUX 和 UNDO 表空間的時間點復原 (PITR)
* 表空間的 PITR 不能與其他類型的復原一起執行
* 如果表空間被重新命名，並且您想要將其還原到重新命名之前的某個時間點，則應指定表空間的早期名稱
* 如果一個表空間中的表的限制包含在另一個表空間中，則應該恢復這兩個表空間
* 如果表及其索引儲存在不同的表空間中，則應在執行 PITR 之前刪除索引
* PITR 不能用於恢復目前預設表空間
* PITR 不能用於復原包含下列任何物件的表空間：
+
** 具有底層物件（例如物化視圖）或包含物件（例如分區表）的對象，除非所有底層物件或包含物件都在復原集中
+
此外，如果分割表的分割區儲存在不同的表空間中，那麼您應該在執行 PITR 之前刪除該表，或者在執行 PITR 之前將所有分割區移動到同一個表空間。

** 撤銷或回滾段
** 具有多個接收者的 Oracle 8 相容高階佇列
** SYS 使用者擁有的對象
+
這些類型的物件的範例有 PL/SQL、Java 類別、呼叫程式、檢視、同義詞、使用者、權限、維度、目錄和序列。







== 還原 Oracle 資料庫的來源和目標

您可以從主儲存或輔助儲存上的備份副本還原 Oracle 資料庫。您只能將資料庫還原到同一資料庫執行個體上的相同位置。但是，在 Real Application Cluster (RAC) 設定中，您可以將資料庫還原到其他節點。



=== 恢復操作的來源

您可以從主儲存或輔助儲存上的備份還原資料庫。如果要從多鏡像配置中的輔助儲存上的備份進行恢復，則可以選擇輔助儲存鏡像作為來源。



=== 恢復操作的目標

您只能將資料庫還原到同一資料庫執行個體上的相同位置。

在 RAC 設定中，您可以從叢集中的任何節點還原 RAC 資料庫。
