---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenter使用憑證對SnapCenter操作的使用者進行身份驗證。您應該建立用於安裝插件包的憑證以及用於對資料庫執行資料保護操作的附加憑證。 
---
= 為 Windows 版SnapCenter插件設定憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter使用憑證對SnapCenter操作的使用者進行身份驗證。您應該建立用於安裝插件包的憑證以及用於對資料庫執行資料保護操作的附加憑證。

.關於此任務
您必須設定在 Windows 主機上安裝插件的憑證。雖然您可以在部署主機和安裝插件後為 Windows 建立憑證，但最佳做法是在新增 SVM 之後、部署主機和安裝插件之前建立憑證。

設定具有管理員權限的憑證，包括遠端主機上的管理員權限。

如果您為單一資源群組設定憑證，且使用者名稱沒有完全管理權限，則必須至少為該使用者名稱指派資源群組和備份權限。

.步驟
. 在左側導覽窗格中，按一下「*設定*」。
. 在「設定」頁面中，按一下「*憑證*」。
. 點選“*新建*”。
+
將顯示“憑證”視窗。

. 在「憑證」頁面中，執行下列操作：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
憑證名稱
 a| 
輸入憑證的名稱。



 a| 
使用者名稱
 a| 
輸入用於身份驗證的使用者名稱。

** 網域管理員或管理員群組的任何成員
+
指定要安裝SnapCenter插件的系統上的網域管理員或管理員群組的任何成員。用戶名字段的有效格式為：

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** 本機管理員（僅適用於工作群組）
+
對於屬於工作群組的系統，請在要安裝SnapCenter插件的系統上指定內建的本機管理員。如果使用者帳戶具有提升的權限或主機系統上停用了使用者存取控制功能，則可以指定屬於本機管理員群組的本機使用者帳戶。用戶名字段的有效格式為： `UserName`





 a| 
密碼
 a| 
輸入用於身份驗證的密碼。



 a| 
驗證
 a| 
選擇 Windows 作為身份驗證模式。

|===
. 按一下“*確定*”。

