---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: '在建立備份作業之前定義備份策略有助於確保您擁有成功還原資料庫所需的備份。您的服務等級協定 (SLA)、復原時間目標 (RTO) 和復原點目標 (RPO) 在很大程度上決定了您的備份策略。' 
---
= 定義 Exchange Server 資源的備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在建立備份作業之前定義備份策略有助於確保您擁有成功還原資料庫所需的備份。您的服務等級協定 (SLA)、復原時間目標 (RTO) 和復原點目標 (RPO) 在很大程度上決定了您的備份策略。

SLA 定義了預期的服務等級並解決了許多與服務相關的問題，包括服務的可用性和效能。  RTO 是指服務中斷後必須恢復業務流程的時間。  RPO 定義了必須從備份儲存中復原的檔案的年齡策略，以便在故障後復原常規作業。  SLA、RTO 和 RPO 有助於備份策略。



== Exchange 資料庫支援的備份類型

使用SnapCenter備份 Exchange 信箱需要您選擇資源類型，例如資料庫和資料庫可用性群組 (DAG)。利用快照技術來建立資源所在磁碟區的線上、唯讀副本。

|===
| 備份類型 | 描述 


 a| 
完整備份和日誌備份
 a| 
備份資料庫和所有交易日誌，包括截斷的日誌。

完整備份完成後，Exchange Server 會截斷已提交至資料庫的交易日誌。

通常，您應該選擇此選項。但是，如果您的備份時間很短，您可以選擇不執行交易日誌備份，而是進行完整備份。



 a| 
完整備份
 a| 
備份資料庫和交易日誌。

截斷的交易日誌不會備份。



 a| 
日誌備份
 a| 
備份所有交易日誌。

已提交到資料庫的截斷日誌不會備份。如果您在完整資料庫備份之間安排頻繁的交易日誌備份，則可以選擇粒度復原點。

|===


== 資料庫插件的備份計劃

備份頻率（計畫類型）在策略中指定；備份計畫在資源組配置中指定。確定備份頻率或計劃的最關鍵因素是資源的變化率和資料的重要性。您可能每小時備份一次使用頻繁的資源，而可能每天備份一次很少使用的資源。其他因素包括資源對您的組織的重要性、您的服務等級協定 (SLA) 和您的復原點目標 (RPO)。

SLA 定義了預期的服務等級並解決了許多與服務相關的問題，包括服務的可用性和效能。  RPO 定義了必須從備份儲存中復原的檔案的年齡策略，以便在故障後復原常規作業。  SLA 和 RPO 有助於資料保護策略。

即使是使用頻繁的資源，也不需要每天執行一次或兩次以上的完整備份。例如，定期的交易日誌備份可能足以確保您擁有所需的備份。備份資料庫的頻率越高， SnapCenter在復原時需要使用的交易日誌就越少，因此可以加快復原作業的速度。

備份計畫分為兩部分，如下所示：

* 備份頻率
+
備份頻率（執行備份的頻率），對於某些外掛程式來說稱為_計畫類型_，是策略配置的一部分。您可以選擇每小時、每天、每週或每月作為策略的備份頻率。如果您未選擇任何頻率，則建立的策略是僅按需策略。您可以透過點選「*設定*」>「*策略*」來存取策略。

* 備份計劃
+
備份計畫（確切地指定執行備份的時間）是資源組配置的一部分。例如，如果您有一個資源組，該資源組的策略配置為每週備份，則可以將計劃配置為每週四晚上 10:00 進行備份。您可以透過點選「*資源*」>「*資源群組*」來存取資源組計畫。





== 資料庫所需的備份作業數量

決定所需備份作業數量的因素包括資源的大小、使用的磁碟區數、資源的變化率以及服務等級協定 (SLA)。



== 備份命名約定

您可以使用預設快照命名約定，也可以使用自訂命名約定。預設備份命名約定會在快照名稱中新增時間戳，以協助您識別副本的建立時間。

快照使用以下預設命名約定：

`resourcegroupname_hostname_timestamp`

您應該對備份資源組進行邏輯命名，如下例所示：

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
在這個例子中，語法元素具有以下含義：

* _dts1_ 是資源組名稱。
* _mach1x88_ 是主機名稱。
* _03-12-2015_23.17.26_ 是日期和時間戳記。


或者，您可以在保護資源或資源群組時選擇「使用自訂名稱格式進行 Snapshot 複製」來指定 Snapshot 名稱格式。例如，customtext_resourcegroup_policy_hostname 或 resourcegroup_hostname。預設情況下，時間戳後綴會加入到快照名稱中。



== 備份保留選項

您可以選擇保留備份副本的天數，或指定要保留的備份副本數量， ONTAP最多可保留 255 份。例如，您的組織可能要求您保留 10 天的備份副本或 130 份備份副本。

建立策略時，您可以指定備份類型和計畫類型的保留選項。

如果您設定了SnapMirror複製，則保留政策將在目標磁碟區上鏡像。

SnapCenter會刪除具有與計劃類型相符的保留標籤的保留備份。如果資源或資源群組的計劃類型發生更改，則具有舊計劃類型標籤的備份可能仍保留在系統中。


NOTE: 為了長期保留備份副本，您應該使用SnapVault備份。



== 在 Exchange Server 的來源儲存磁碟區上保留交易日誌備份的時間

適用於 Microsoft Exchange Server 的SnapCenter外掛程式需要交易日誌備份來執行最新的還原作業，該操作將資料庫還原到兩次完整備份之間的時間。

例如，如果 Plug-in for Exchange 在上午 8:00 進行了一次完整備份和交易日誌備份，並在下午 5:00 進行了另一次完整備份和交易日誌備份，則它可以使用最新的交易日誌備份將資料庫還原到上午 8:00 至下午 5:00 之間的任何時間。如果沒有交易日誌，Plug-in for Exchange 只能執行時間點還原作業，即將資料庫還原到 Plug-in for Exchange 完成完整備份的時間。

通常，您只需要一兩天的最新恢復操作。預設情況下， SnapCenter至少保留兩天。
