---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: 您可以在使用SnapCenter備份 Microsoft Exchange Server 資源之前為 Exchange 資源或資源群組建立備份原則，也可以在建立資源群組或備份單一資源時建立備份原則。 
---
= 為 Exchange Server 資料庫建立備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在使用SnapCenter備份 Microsoft Exchange Server 資源之前為 Exchange 資源或資源群組建立備份原則，也可以在建立資源群組或備份單一資源時建立備份原則。

.開始之前
* 您必須已經定義了您的資料保護策略。
+
有關詳細信息，請參閱有關定義 Exchange 資料庫的資料保護策略的資訊。

* 您必須透過完成安裝SnapCenter、新增主機、識別資源和建立儲存系統連線等任務來為資料保護做好準備。
* 您必須刷新（發現）Exchange Server 資源。
* 如果您要將快照複製到映像或保管庫， SnapCenter管理員必須已為您指派來源磁碟區和目標磁碟區的儲存虛擬機器 (SVM)。
* 如果要在前言和後言中執行 PowerShell 腳本，則應設定 `usePowershellProcessforScripts`參數為 true `web.config`文件。
+
預設值為 false。

* 查看SnapMirror主動同步特定的先決條件和限制。欲了解詳細信息，請參閱 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror主動同步的物件限制"]。


.關於此任務
* 備份策略是一組規則，用於控制如何管理和保留備份以及資源或資源群組的備份頻率。此外，您也可以指定腳本設定。當您想要將策略重新用於另一個資源群組時，在策略中指定選項可以節省時間。
* 完整備份保留特定於給定的策略。使用策略 A 且完整備份保留期為 4 的資料庫或資源將保留 4 個完整備份，並且對相同資料庫或資源的策略 B 沒有影響，策略 B 可能具有保留期為 3 以保留 3 個完整備份。
* 日誌備份保留跨策略有效，並適用於資料庫或資源的所有日誌備份。因此，當使用策略 B 執行完整備份時，日誌保留設定會影響策略 A 在相同資料庫或資源上建立的日誌備份。同樣，策略 A 的日誌保留設定會影響策略 B 在相同資料庫上建立的日誌備份。
* SCRIPTS_PATH 是使用插件主機的 SMCoreServiceHost.exe.Config 檔案中的 PredefinedWindowsScriptsDirectory 鍵定義的。
+
如果需要，您可以變更此路徑並重新啟動 SMcore 服務。為了安全起見，建議您使用預設路徑。

+
可以透過 API 從 Swagger 顯示該鍵的值：API /4.7/configsettings

+
您可以使用 GET API 來顯示鍵的值。不支援 SET API。

+
|===


| *最佳實務：*最好根據您想要保留的完整備份和日誌備份的總數來設定輔助保留策略。配置輔助保留策略時，請記住，當資料庫和日誌位於不同的磁碟區時，每個備份可以有三個快照，而當資料庫和日誌位於同一磁碟區時，每個備份可以有兩個快照。 
|===
* SnapLock
+
** 如果選擇了「保留備份副本特定天數」選項，則SnapLock保留期必須小於或等於上述保留天數。
+
指定快照鎖定期可防止在保留期到期之前刪除快照。這可能導致保留的快照數量超過策略中指定的數量。

+
對於ONTAP 9.12.1 及以下版本、從SnapLock Vault 快照建立的克隆將繼承SnapLock Vault 到期時間。儲存管理員應在SnapLock到期後手動清理克隆。





.步驟
. 在左側導覽窗格中，按一下「*設定*」。
. 在「設定」頁面中，按一下「*策略*」。
. 點選“*新建*”。
. 在名稱頁面中，輸入策略名稱和詳細資訊。
. 在備份類型和複製頁面中，執行下列步驟：
+
.. 選擇備份類型：
+
|===
| 如果你想... | 這樣做... 


 a| 
備份資料庫檔案和所需的交易日誌
 a| 
選擇*完整備份和日誌備份*。

資料庫採用日誌截斷備份，備份所有日誌，包括被截斷的日誌。


NOTE: 這是建議的備份類型。



 a| 
備份資料庫檔案和未提交的交易日誌
 a| 
選擇*完整備份*。

資料庫備份時會進行日誌截斷，截斷的日誌不會備份。



 a| 
備份所有交易日誌
 a| 
選擇*日誌備份*。

活動檔案系統上的所有交易日誌都已備份，且沒有日誌截斷。

在與即時日誌相同的磁碟上建立 _scebackupinfo_ 目錄。該目錄包含指向 Exchange 資料庫增量變更的指針，它並不等同於完整的日誌檔案。



 a| 
備份所有資料庫檔案和交易日誌，而不截斷交易日誌文件
 a| 
選擇*複製備份*。

所有資料庫和所有日誌均已備份，且沒有日誌截斷。您通常使用此備份類型來重新播種副本或測試或診斷問題。

|===
+

NOTE: 您應該根據完整備份保留而不是最新 (UTM) 保留來定義日誌備份所需的空間。

+

NOTE: 處理 Exchange 磁碟區 (LUN) 時，為日誌和資料庫建立單獨的保管庫策略，並使用相同的標籤將日誌策略的保留 (keep) 設定為資料庫策略的每個標籤數量的兩倍。欲了解更多信息，請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_for_Exchange_Backups_only_keep_half_the_Snapshots_on_the_Vault_destination_log_volume["SnapCenter for Exchange 備份僅保留 Vault 目標日誌磁碟區上的一半快照"^]

.. 在資料庫可用性群組設定部分中，選擇一個操作：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
備份活動副本
 a| 
選擇此選項可僅備份所選資料庫的活動副本。

對於資料庫可用性群組 (DAG)，此選項僅備份 DAG 中所有資料庫的活動副本。

被動副本未備份。



 a| 
在建立備份作業時選擇的伺服器上備份副本
 a| 
選擇此選項可備份選定伺服器（主動伺服器和被動伺服器）上資料庫的任何副本。

對於 DAG，此選項將備份選定伺服器上所有資料庫的主動副本和被動副本。

|===
+

NOTE: 在叢集配置中，備份會根據策略中設定的保留設定保留在叢集的每個節點上。如果叢集的擁有者節點發生變化，則會保留前一個所有者節點的備份。保留僅適用於節點層級。

.. 在「計畫頻率」部分中，選擇一種或多種頻率類型：*按需*、*每小時*、*每天*、*每週*和*每月*。
+

NOTE: 您可以在建立資源組時指定備份作業的計畫（開始日期、結束日期）。這使您能夠建立共享相同策略和備份頻率的資源群組，但允許您為每個策略指派不同的備份計劃。

+

NOTE: 如果您已安排在凌晨 2:00，則夏令時 (DST) 期間不會觸發該計劃。

.. 選擇策略標籤。
+

NOTE: 您可以為遠端複製的主快照指派SnapMirror標籤，從而允許主快照將快照複製作業從SnapCenter卸載到ONTAP二級系統。無需在策略頁面中啟用SnapMirror或SnapVault選項即可完成此操作。

.. 在「選擇輔助複製選項」部分中，選擇以下一個或兩個輔助複製選項：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
建立本地快照後更新SnapMirror
 a| 
選擇此選項可在另一個磁碟區上保留備份集的鏡像副本（SnapMirror）。

在二次複製期間， SnapLock到期時間會載入主SnapLock到期時間。

應為SnapMirror主動同步啟用此選項。


IMPORTANT: 如果為 Exchange ONTAP磁碟區設定了SnapMirror主動同步，則無法使用僅主原則。 SnapCenter不允許這樣做。您應該啟用“鏡像”選項。

點選拓樸頁面中的「*刷新*」按鈕可重新整理從ONTAP擷取的輔助和主SnapLock到期時間。

看link:../protect-sce/task_view_exchange_backups_in_the_topology_page.html["在拓樸頁面中查看 Exchange 備份"] 。



 a| 
建立本機快照後更新SnapVault
 a| 
選擇此選項可執行磁碟到磁碟的備份複製。



 a| 
錯誤重試次數
 a| 
輸入進程停止之前應發生的複製嘗試次數。

|===
+

NOTE: 您應該在ONTAP中為二級儲存配置SnapMirror保留策略，以避免達到二級儲存上快照的最大限制。



. 在保留頁面中，配置保留設定。
+
顯示的選項取決於您先前選擇的備份類型和頻率類型。

+

NOTE: 最大保留值為 1018。如果保留設定的值高於底層ONTAP版本支援的值，則備份將會失敗。

+

IMPORTANT: 如果您打算啟用SnapVault複製，則必須將保留計數設為 2 或更高。如果將保留計數設為 1，則保留操作可能會失敗，因為第一個快照是SnapVault關係的參考快照，直到較新的快照複製到目標。

+
.. 在「日誌備份保留設定」部分中，選擇下列選項之一：
+
|===
| 如果你想... | 這樣做... 


 a| 
僅保留特定數量的日誌備份
 a| 
選擇*保留日誌的完整備份數*，並指定您想要最新還原的完整備份數。

最新 (UTM) 保留適用於透過完整或日誌備份建立的日誌備份。例如，如果將 UTM 保留設定配置為保留最近 5 次完整備份的日誌備份，則會保留最近 5 次完整備份的日誌備份。

作為完整和日誌備份的一部分建立的日誌資料夾將作為 UTM 的一部分自動刪除。您不能手動刪除日誌資料夾。例如，如果完整或完整和日誌備份的保留設定設為 1 個月，而 UTM 保留設定為 10 天，則作為這些備份的一部分建立的日誌資料夾將根據 UTM 刪除。因此，只有 10 天的日誌資料夾會存在，並且所有其他備份都標記為時間點復原。

如果您不想執行最新恢復，可以將 UTM 保留值設為 0。這將啟用時間點恢復操作。

*最佳實務：*最好該設定必須等於完整備份保留設定部分中的總快照（完整備份）的設定。這可確保每次完整備份時都保留日誌檔案。



 a| 
將備份副本保留特定天數
 a| 
選擇「保留最後的日誌備份」選項，並指定保留日誌備份副本的天數。

日誌備份最多保留完整備份的天數。



 a| 
快照鎖定期
 a| 
選擇*Snapshot 副本鎖定期限*，並選擇天、月或年。

SnapLock保留期應少於 100 年。

|===
+
如果您選擇「*日誌備份*」作為備份類型，則日誌備份將保留為完整備份的最新保留設定的一部分。

.. 在完整備份保留設定部分中，為按需備份選擇以下選項之一，然後為完整備份選擇一個：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
僅保留特定數量的快照
 a| 
如果要指定要保留的完整備份數量，請選擇*要保留的 Snapshot 副本總數*選項，並指定要保留的快照（完整備份）數量。

如果完整備份的數量超過指定數量，則會刪除超過指定數量的完整備份，並先刪除最舊的副本。



 a| 
保留完整備份特定天數
 a| 
選擇「保留快照副本」選項，並指定保留快照（完整備份）的天數。



 a| 
主快照鎖定期
 a| 
選擇*主快照副本鎖定期限*，並選擇天、月或年。

SnapLock保留期應少於 100 年。



 a| 
二級快照鎖定期
 a| 
選擇*次快照副本鎖定期限*，並選擇天、月或年。

|===
+
如果 DAG 配置中的主機上有一個僅具有日誌備份而沒有完整備份的資料庫，則日誌備份將透過以下方式保留：

+
*** 預設情況下， SnapCenter會在 DAG 中的所有其他主機中尋找此資料庫的最早完整備份，並刪除在完整備份之前在此主機上進行的所有日誌備份。
*** 您可以透過在 _C:\Program Files\ NetApp\ SnapCenter WebApp\web.config_ 檔案中新增按鍵 *MaxLogBackupOnlyCountWithoutFullBackup* 來覆寫僅具有日誌備份的 DAG 中主機上的資料庫的上述預設保留行為。
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
在範例中，值 10 表示您在主機上保留最多 10 個日誌備份。





. 在腳本頁面中，分別輸入應在備份作業之前或之後執行的前置腳本或後置腳本的路徑和參數。
+
** 預設備份參數包括“$Database”和“$ServerInstance”。
** Postscript 備份參數包括「$Database」、「$ServerInstance」、「$BackupName」、「$LogDirectory」和「$LogSnapshot」。
+
您可以執行腳本來更新 SNMP 陷阱、自動發出警報、發送日誌等。

+

NOTE: 前言或後記路徑不應包含磁碟機或共用。該路徑應相對於 SCRIPTS_PATH。



. 查看摘要，然後按一下「*完成*」。

