---
permalink: protect-scw/concept_snapcenter_plug_in_for_windows_features.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Windows 插件與儲存系統上的NetApp Snapshot 技術整合。若要使用適用於 Windows 的插件，您需要使用SnapCenter介面。 
---
= 適用於 Windows 的SnapCenter插件功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 插件與儲存系統上的NetApp Snapshot 技術整合。若要使用適用於 Windows 的插件，您需要使用SnapCenter介面。

Windows 外掛程式包括以下主要功能：

* *由SnapCenter提供支援的統一圖形使用者介面*
+
SnapCenter介面為您提供跨插件和環境的標準化和一致性。  SnapCenter介面可讓您跨外掛程式完成一致的備份和復原流程、使用集中式報表、使用一目了然的儀表板視圖、設定基於角色的存取控制 (RBAC) 以及監控所有外掛程式中的作業。  SnapCenter還提供集中調度和策略管理以支援備份和複製作業。

* *自動化中央管理*
+
您可以安排例行檔案系統備份、設定基於政策的備份保留以及設定復原作業。您也可以透過設定SnapCenter發送電子郵件警報來主動監控您的檔案系統環境。

* *無中斷NetApp Snapshot 技術*
+
Windows 插件使用NetApp Snapshot 技術。這使您能夠在幾秒鐘內備份檔案系統並快速恢復它們，而無需使主機離線。快照佔用的儲存空間極小。



除了這些主要功能外，Windows 外掛還提供以下優點：

* 備份、還原和克隆工作流程支持
* RBAC 支援的安全性和集中角色委派
* 使用NetApp FlexClone技術建立生產檔案系統的空間高效副本，用於測試或資料擷取
+
有關FlexClone許可信息，請參閱link:../get-started/concept_snapcenter_licenses.html["SnapCenter許可證"^]。

* 能夠在多台伺服器上同時執行多個備份
* 用於編寫備份、還原和複製作業腳本的 PowerShell cmdlet
* 支援檔案系統和虛擬機器磁碟（VMDK）的備份
* 支援實體和虛擬化基礎設施
* 支援 iSCSI、光纖通道、FCoE、原始裝置對映 (RDM)、非對稱 LUN 對映 (ALM)、NFS 和 VMFS 上的 VMDK 以及虛擬 FC
* Windows Server 2022 支援非揮發性記憶體快速 (NVMe)
+
** 在 TCP/IP 上的 NVMe 上建立的 VMDK 佈局的備份、復原、複製和驗證工作流程。
** 從 ESX 8.0 update 2 開始支援 NVMe 韌體版本 1.3，並且需要虛擬硬體版本 21。
** NVMe over TCP/IP 上的 VMDK 應用程式不支援 Windows Server 故障轉移叢集 (WSFC)。


* 支援SnapMirror主動同步（最初作為SnapMirror業務連續性 [SM-BC] 發布），即使整個網站發生故障，也能使業務服務繼續運行，支援應用程式使用輔助副本透明地進行故障轉移。無需手動幹預或額外的腳本即可透過SnapMirror主動同步觸發故障轉移。

