---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup policy 
summary: 您可以在使用SnapCenter備份 Windows 檔案系統之前為資源建立新的備份策略，也可以在建立資源群組或備份資源時建立新的備份策略。 
---
= 為 Windows 檔案系統建立備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在使用SnapCenter備份 Windows 檔案系統之前為資源建立新的備份策略，也可以在建立資源群組或備份資源時建立新的備份策略。

.開始之前
* 您必須已經定義了您的備份策略。link:task_define_a_backup_strategy_for_windows_file_systems.html["了解更多"^]
* 您必須做好資料保護的準備。
+
為了準備資料保護，您必須完成安裝SnapCenter、新增主機、發現資源和建立儲存虛擬機器 (SVM) 連線等任務。

* 如果您要將快照複製到映像或保管庫二級存儲， SnapCenter管理員必須已為您指派來源磁碟區和目標磁碟區的 SVM。
* 如果您想要在前腳本和後腳本中執行 PowerShell 腳本，則應在 web.config 檔案中將 usePowershellProcessforScripts 參數的值設為 true。
+
預設值為 false

* 查看SnapMirror主動同步特定的先決條件和限制。欲了解詳細信息，請參閱 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror主動同步的物件限制"]。


.關於此任務
* SCRIPTS_PATH 是使用插件主機的 SMCoreServiceHost.exe.Config 檔案中的 PredefinedWindowsScriptsDirectory 鍵定義的。
+
如果需要，您可以變更此路徑並重新啟動 SMcore 服務。為了安全起見，建議您使用預設路徑。

+
可以透過 API 從 Swagger 顯示該鍵的值：API /4.7/configsettings

+
您可以使用 GET API 來顯示鍵的值。不支援 SET API。

* SnapLock
+
** 如果選擇了「保留備份副本特定天數」選項，則SnapLock保留期必須小於或等於上述保留天數。
** 指定快照鎖定期可防止在保留期到期之前刪除快照。這可能導致保留的快照數量超過策略中指定的數量。
** 對於ONTAP 9.12.1 及以下版本、作為復原的一部分從SnapLock Vault 快照建立的克隆將繼承SnapLock Vault 到期時間。儲存管理員應在SnapLock到期後手動清理克隆。




.步驟
. 在左側導覽窗格中，選擇「*設定*」。
. 在設定頁面中，選擇*策略*。
. 選擇“*新建*”。
. 在名稱頁面中，輸入策略名稱和詳細資訊。
. 在「備份和複製」頁面中，執行下列任務：
+
.. 選擇備份設定。
+
|===
| 選項 | 描述 


 a| 
檔案系統一致性備份
 a| 
如果您希望SnapCenter在備份作業開始之前將檔案系統所在的磁碟機置於靜止狀態，然後在備份作業結束後還原磁碟機，請選擇此選項。



 a| 
檔案系統崩潰一致性備份
 a| 
如果您不希望SnapCenter使檔案系統所在的磁碟機處於靜止狀態，請選擇此選項。

|===
.. 選擇計劃頻率（也稱為策略類型）。
+
此策略僅指定備份頻率。備份的具體保護計劃在資源組中定義。因此，兩個或多個資源組可以共享相同的策略和備份頻率，但具有不同的備份計劃。

+

NOTE: 如果您已安排在凌晨 2:00，則夏令時 (DST) 期間不會觸發該計劃。

.. 選擇一個策略標籤。
+
根據您選擇的快照標籤， ONTAP將套用與該標籤相符的輔助快照保留策略。

+

NOTE: 如果您選擇了*建立本機 Snapshot 副本後更新SnapMirror *，則可以選擇指定輔助原則標籤。但是，如果您選擇了*建立本機 Snapshot 副本後更新SnapVault *，則應指定輔助原則標籤。



. 在「選擇輔助複製選項」部分中，選擇以下一個或兩個輔助複製選項：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
建立本地 Snapshot 副本後更新SnapMirror
 a| 
選擇此選項可在另一個磁碟區上建立備份集的鏡像副本（SnapMirror）。

應為 SnapSnapMirror 主動同步啟用此選項。

在二次複製期間， SnapLock到期時間會載入主SnapLock到期時間。點選拓樸頁面中的「*刷新*」按鈕可重新整理從ONTAP擷取的輔助和主SnapLock到期時間。

看link:../protect-scw/task_view_related_backups_and_clones_in_the_topology_page.html["在拓撲頁面中查看相關備份和克隆"] 。



 a| 
建立 Snapshot 副本後更新SnapVault
 a| 
選擇此選項可執行磁碟到磁碟的備份複製。

在二次複製期間， SnapLock到期時間會載入主SnapLock到期時間。點選拓樸頁面中的刷新按鈕可重新整理從ONTAP擷取的輔助和主SnapLock到期時間。

當僅在ONTAP的輔助節點（稱為SnapLock Vault）上配置SnapLock時，按一下「拓撲」頁面中的「刷新」按鈕將刷新從ONTAP檢索到的輔助節點上的鎖定期限。

有關SnapLock Vault 的更多信息，請參閱 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["將 Snapshot 副本提交到保管庫目標上的 WORM"]



 a| 
錯誤重試次數
 a| 
輸入進程停止之前應發生的複製嘗試次數。

|===
+

NOTE: 您應該在ONTAP中為二級儲存配置SnapMirror保留策略，以避免達到二級儲存上快照的最大限制。

. 在「保留設定」頁面中，指定按需備份和所選每個計畫頻率的保留設定。
+
|===
| 選項 | 描述 


 a| 
要保留的 Snapshot 副本總數
 a| 
如果您想在自動刪除快照之前指定SnapCenter儲存的快照數量，請選擇此選項。



 a| 
保留 Snapshot 副本
 a| 
如果您想要指定SnapCenter在刪除備份副本之前保留該副本的天數，請選擇此選項。



 a| 
快照副本鎖定期
 a| 
選擇快照鎖定期限，並指定持續時間（天、月或年）。

SnapLock保留期應少於 100 年。

|===
+

IMPORTANT: 您應該將保留計數設為 2 或更高。保留計數的最小值為 2。

+

NOTE: 最大保留值為 1018。如果保留設定的值高於ONTAP版本支援的值，則備份將會失敗。

. 在腳本頁面中，分別輸入您希望SnapCenter伺服器在備份作業之前或之後執行的前腳本或後置腳本的路徑，以及SnapCenter在逾時之前等待腳本執行的時間限制。
+
例如，您可以執行腳本來更新 SNMP 陷阱、自動發出警報和傳送日誌。

+

NOTE: 前言或後記路徑不應包含磁碟機或共用。該路徑應相對於 SCRIPTS_PATH。

. 查看摘要，然後按一下「*完成*」。

