---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup strategy 
summary: '在建立備份之前定義備份策略可為您提供成功復原或複製檔案系統所需的備份。您的服務等級協定 (SLA)、復原時間目標 (RTO) 和復原點目標 (RPO) 在很大程度上決定了您的備份策略。' 
---
= 定義 Windows 檔案系統的備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在建立備份之前定義備份策略可為您提供成功復原或複製檔案系統所需的備份。您的服務等級協定 (SLA)、復原時間目標 (RTO) 和復原點目標 (RPO) 在很大程度上決定了您的備份策略。

SLA 定義了預期的服務等級並解決了許多與服務相關的問題，包括服務的可用性和效能。  RTO 是服務中斷後必須恢復業務流程的時間。  RPO 定義了必須從備份儲存中復原的檔案的年齡策略，以便在故障後復原常規作業。  SLA、RTO 和 RPO 有助於資料保護策略。



== Windows 檔案系統的備份計劃

備份頻率在策略中指定；備份計畫在資源組配置中指定。確定備份頻率或計劃的最關鍵因素是資源的變化率和資料的重要性。您可能每小時備份一次使用頻繁的資源，而可能每天備份一次不常用的資源。其他因素包括資源對您的組織的重要性、您的服務等級協定 (SLA) 和您的復原點目標 (RPO)。

SLA 定義了預期的服務等級並解決了許多與服務相關的問題，包括服務的可用性和效能。  RPO 定義了必須從備份儲存中復原的檔案的年齡策略，以便在故障後復原常規作業。  SLA 和 RPO 有助於資料保護策略。

即使是使用頻繁的資源，也不需要每天執行一次或兩次以上的完整備份。

備份計畫分為兩部分，如下所示：

* 備份頻率
+
備份頻率（執行備份的頻率），對於某些外掛程式來說稱為_計畫類型_，是策略配置的一部分。例如，您可以將備份頻率配置為每小時、每天、每週或每月，或者您可以指定 *None*，這使該策略成為僅按需策略。您可以透過點選「*設定*」>「*策略*」來存取策略。

* 備份計劃
+
備份計畫（確切地指定執行備份的時間）是資源組配置的一部分。例如，如果您有一個資源組，該資源組的策略配置為每週備份，則可以將計劃配置為每週四晚上 10:00 進行備份。您可以透過點選「*資源*」>「*資源群組*」來存取資源組計畫。





== Windows 檔案系統所需的備份數量

決定所需備份數量的因素包括 Windows 檔案系統的大小、使用的磁碟區數、檔案系統的變化率以及您的服務等級協定 (SLA)。



== Windows 檔案系統的備份命名約定

Windows 檔案系統備份使用預設的快照命名約定。預設備份命名約定會在快照名稱中新增時間戳，以協助您識別副本的建立時間。

快照使用以下預設命名約定：resourcegroupname_hostname_timestamp

您應該對備份資源組進行邏輯命名，如下例所示：

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
在這個例子中，語法元素具有以下含義：

* `dts1`是資源組名稱。
* `mach1x88`是主機名稱。
* `03-12-2016_23.17.26`是日期和時間戳。


建立備份時，您也可以新增描述性標籤來協助識別備份。相反，如果您想使用自訂的備份命名約定，則需要在備份作業完成後重新命名備份。



== 備份保留選項

您可以選擇保留備份副本的天數，或指定要保留的備份副本數量， ONTAP最多可保留 255 份。例如，您的組織可能要求您保留 10 天的備份副本或 130 份備份副本。

建立策略時，您可以指定備份類型和計畫類型的保留選項。

如果您設定了SnapMirror複製，則保留政策將在目標磁碟區上鏡像。

SnapCenter會刪除具有與計劃類型相符的保留標籤的保留備份。如果資源或資源群組的計劃類型發生更改，則具有舊計劃類型標籤的備份可能仍保留在系統中。


NOTE: 為了長期保留備份副本，您應該使用SnapVault備份。
