---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: 您可以使用SnapCenter克隆 Windows 檔案系統備份。如果您想要錯誤刪除或更改的單一檔案的副本，那麼您可以複製備份並在複製中存取該檔案。 
---
= 從 Windows 檔案系統備份克隆
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用SnapCenter克隆 Windows 檔案系統備份。如果您想要錯誤刪除或更改的單一檔案的副本，那麼您可以複製備份並在複製中存取該檔案。

.開始之前
* 您應該已經透過完成新增主機、識別資源和建立儲存虛擬機器 (SVM) 連線等任務為資料保護做好了準備。
* 您應該有一個檔案系統的備份。
* 您應確保託管磁碟區的聚合位於儲存虛擬機器 (SVM) 的已指派聚合清單中。
* 您不能克隆資源組。您只能克隆單一檔案系統備份。
* 如果備份駐留在具有 VMDK 磁碟的虛擬機器上，則SnapCenter無法將備份複製到實體伺服器。
* 如果您複製 Windows 叢集（例如，共用 LUN 或叢集共用磁碟區 (CSV) LUN），則複製將作為專用 LUN 儲存在您指定的主機上。
* 對於克隆操作，卷掛載點的根目錄不能是共享目錄。
* 您不能在非聚合主節點上建立克隆。
* 您無法為 Windows 檔案系統安排重複複製（複製生命週期）操作；您只能按需複製備份。
* 如果將包含複製的 LUN 移至新磁碟區， SnapCenter將不再支援該複製。例如，您不能使用SnapCenter刪除該克隆。
* 您不能跨環境克隆。例如，從實體磁碟複製到虛擬磁碟或反之亦然。


.關於此任務
* SCRIPTS_PATH 是使用插件主機的 SMCoreServiceHost.exe.Config 檔案中的 PredefinedWindowsScriptsDirectory 鍵定義的。
+
如果需要，您可以變更此路徑並重新啟動 SMcore 服務。為了安全起見，建議您使用預設路徑。

+
可以透過 API 從 Swagger 顯示該鍵的值：API /4.7/configsettings

+
您可以使用 GET API 來顯示鍵的值。不支援 SET API。

* 對於ONTAP 9.12.1 及以下版本、作為復原的一部分從SnapLock Vault 快照建立的克隆將繼承SnapLock Vault 到期時間。儲存管理員應在SnapLock到期後手動清理克隆。


[role="tabbed-block"]
====
.SnapCenter使用者介面
--
.步驟
. 在左側導覽窗格中，按一下“*資源*”，然後從清單中選擇適當的外掛程式。
. 在資源頁面中，從清單中選擇*檔案系統*。
. 選擇主機。
+
如果資源受到保護，則會自動顯示拓樸視圖。

. 從資源清單中，選擇要複製的備份，然後按一下複製圖示。
. 在「選項」頁面中，執行以下操作：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
克隆伺服器
 a| 
選擇要建立克隆的主機。



 a| 
“自動分配掛載點”或“自動分配路徑下的磁碟區掛載點”
 a| 
選擇是否自動指派掛載點或路徑下的磁碟區掛載點。

自動分配路徑下的磁碟區掛載點：路徑下的掛載點可讓您提供將在其中建立掛載點的特定目錄。在選擇此選項之前，您必須驗證目錄是否為空。如果目錄中存在備份，則掛載作業後備份將處於無效狀態。



 a| 
存檔位置
 a| 
如果您要複製輔助備份，請選擇存檔位置。

|===
. 在腳本頁面中，指定您想要執行的任何前腳本或後腳本。
+

NOTE: 前言或後記路徑不應包含磁碟機或共用。該路徑應相對於 SCRIPTS_PATH。

. 查看摘要，然後按一下「*完成*」。
. 透過點選「*監視*」>「*作業*」來監視操作進度。


--
.PowerShell cmdlet
--
.步驟
. 使用 Open-SmConnection cmdlet 為指定使用者啟動與SnapCenter伺服器的連線會話。
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146
----
. 列出可以使用 Get-SmBackup 或 Get-SmResourceGroup cmdlet 克隆的備份。
+
此範例顯示有關所有可用備份的資訊：

+
[listing]
----
C:\PS>PS C:\> Get-SmBackup

BackupId   BackupName                     BackupTime   BackupType
--------   ----------                     ----------   ----------
1          Payroll Dataset_vise-f6_08...  8/4/2015     Full Backup
                                          11:02:32 AM

2          Payroll Dataset_vise-f6_08...  8/4/2015
                                          11:23:17 AM
----
+
此範例顯示有關指定資源組、其資源和相關策略的資訊：

+
[listing]
----
PS C:\> Get-SmResourceGroup -ListResources –ListPolicies

Description :
CreationTime : 8/4/2015 3:44:05 PM
ModificationTime : 8/4/2015 3:44:05 PM
EnableEmail : False
EmailSMTPServer :
EmailFrom :
EmailTo :
EmailSubject :
EnableSysLog : False
ProtectionGroupType : Backup
EnableAsupOnFailure : False
Policies : {FinancePolicy}
HostResourceMaping : {}
Configuration : SMCoreContracts.SmCloneConfiguration
LastBackupStatus :
VerificationServer :
EmailBody :
EmailNotificationPreference : Never
VerificationServerInfo : SMCoreContracts.SmVerificationServerInfo
SchedulerSQLInstance :
CustomText :
CustomSnapshotFormat :
SearchResources : False
ByPassCredential : False
IsCustomSnapshot :
MaintenanceStatus : Production
PluginProtectionGroupTypes : {SMSQL}
Name : Payrolldataset
Type : Group
Id : 1
Host :
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
CloneLevel : 0
ApplySnapvaultUpdate : False
ApplyRetention : False
RetentionCount : 0
RetentionDays : 0
ApplySnapMirrorUpdate : False
SnapVaultLabel :
MirrorVaultUpdateRetryCount : 7
AppPolicies : {}
Description : FinancePolicy
PreScriptPath :
PreScriptArguments :
PostScriptPath :
PostScriptArguments :
ScriptTimeOut : 60000
DateModified : 8/4/2015 3:43:30 PM
DateCreated : 8/4/2015 3:43:30 PM
Schedule : SMCoreContracts.SmSchedule
PolicyType : Backup
PluginPolicyType : SMSQL
Name : FinancePolicy
Type :
Id : 1
Host :
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
CloneLevel : 0
clab-a13-13.sddev.lab.netapp.com
DatabaseGUID :
SQLInstance : clab-a13-13
DbStatus : AutoClosed
DbAccess : eUndefined
IsSystemDb : False
IsSimpleRecoveryMode : False
IsSelectable : True
SqlDbFileGroups : {}
SqlDbLogFiles : {}
AppFileStorageGroups : {}
LogDirectory :
AgName :
Version :
VolumeGroupIndex : -1
IsSecondary : False
Name : TEST
Type : SQL Database
Id : clab-a13-13\TEST
Host : clab-a13-13.sddev.mycompany.com
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
----
. 使用 New-SmClone cmdlet 從現有備援啟動複製作業。
+
此範例從包含所有日誌的指定備份建立複製：

+
[listing]
----
PS C:\> New-SmClone
-BackupName payroll_dataset_vise-f3_08-05-2015_15.28.28.9774
-Resources @{"Host"="vise-f3.sddev.mycompany.com";
"Type"="SQL Database";"Names"="vise-f3\SQLExpress\payroll"}
-CloneToInstance vise-f3\sqlexpress -AutoAssignMountPoint
-Suffix _clonefrombackup
-LogRestoreType All -Policy clonefromprimary_ondemand

PS C:> New-SmBackup -ResourceGroupName PayrollDataset -Policy FinancePolicy
----
+
此範例建立指定 Microsoft SQL Server 執行個體的複製：

+
[listing]
----
PS C:\> New-SmClone
-BackupName "BackupDS1_NY-VM-SC-SQL_12-08-2015_09.00.24.8367"
-Resources @{"host"="ny-vm-sc-sql";"Type"="SQL Database";
"Names"="ny-vm-sc-sql\AdventureWorks2012_data"}
-AppPluginCode SMSQL -CloneToInstance "ny-vm-sc-sql"
-Suffix _CLPOSH -AssignMountPointUnderPath "C:\SCMounts"
----
. 使用 Get-SmCloneReport cmdlet 查看複製作業的狀態。
+
此範例顯示指定作業 ID 的複製報表：

+
[listing]
----
PS C:\> Get-SmCloneReport -JobId 186

SmCloneId : 1
SmJobId : 186
StartDateTime : 8/3/2015 2:43:02 PM
EndDateTime : 8/3/2015 2:44:08 PM
Duration : 00:01:06.6760000
Status : Completed
ProtectionGroupName : Draper
SmProtectionGroupId : 4
PolicyName : OnDemand_Clone
SmPolicyId : 4
BackupPolicyName : OnDemand_Full_Log
SmBackupPolicyId : 1
CloneHostName : SCSPR0054212005.mycompany.com
CloneHostId : 4
CloneName : Draper__clone__08-03-2015_14.43.53
SourceResources : {Don, Betty, Bobby, Sally}
ClonedResources : {Don_DRAPER, Betty_DRAPER, Bobby_DRAPER,
                   Sally_DRAPER}
----


可以透過執行_Get-Help command_name_來取得有關可與 cmdlet 一起使用的參數及其描述的資訊。或者，您也可以參考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter軟體 Cmdlet 參考指南"^]。

--
====