---
permalink: protect-scw/task_add_hosts_and_install_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: installing 
summary: 您可以使用SnapCenter新增主機頁面來新增 Windows 主機。適用於 Microsoft Windows 的SnapCenter外掛程式會自動安裝在指定主機上。這是安裝插件的推薦方法。您可以新增主機並為單一主機或叢集安裝插件。 
---
= 新增主機並安裝適用於 Microsoft Windows 的SnapCenter插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用SnapCenter新增主機頁面來新增 Windows 主機。適用於 Microsoft Windows 的SnapCenter外掛程式會自動安裝在指定主機上。這是安裝插件的推薦方法。您可以新增主機並為單一主機或叢集安裝插件。

.開始之前
* 如果SnapCenter Server 主機的作業系統是 Windows 2019，而插件主機的作業系統是 Windows 2022，則應執行下列操作：
+
** 升級到 Windows Server 2019（作業系統內部版本 17763.5936）或更高版本
** 升級到 Windows Server 2022（作業系統內部版本 20348.2402）或更高版本


* 您必須是分配有插件安裝和卸載權限的角色的用戶，例如SnapCenter管理員角色。
* 在 Windows 主機上安裝插件時，如果指定非內建的憑證或使用者屬於本機工作群組用戶，則必須在主機上停用 UAC。
* 應將SnapCenter使用者新增至 Windows Server 的「作為服務登入」角色。
* 您應該確保訊息佇列服務處於運行狀態。
* 如果您使用群組託管服務帳戶 (gMSA)，則應使用管理權限設定 gMSA。
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["在 Windows Server 2016 或更高版本上為 Windows 檔案系統設定群組託管服務帳戶"]



.關於此任務
* 您不能將SnapCenter伺服器作為插件主機新增至另一個SnapCenter伺服器。
* Windows 外掛
+
** 微軟 Windows
** Microsoft Exchange 伺服器
** 微軟 SQL 伺服器
** SAP HANA


* 在集群上安裝插件
+
如果在叢集（WSFC、Oracle RAC 或 Exchange DAG）上安裝插件，則它們將安裝在叢集的所有節點上。

* E系列儲存
+
您無法在連接到 E 系列儲存的 Windows 主機上安裝適用於 Windows 的插件。




NOTE: 如果主機已經是工作群組的一部分並變更為另一個網域或反之亦然，則SnapCenter不支援將相同主機（插件主機）新增至SnapCenter。如果要新增相同的主機，則應從SnapCenter中刪除該主機，然後重新新增。

.步驟
. 在左側導覽窗格中，按一下「*主機*」。
. 確保在頂部選擇了*託管主機*。
. 按一下“*新增*”。
. 在「主機」頁面中，執行下列操作：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
主機類型
 a| 
選擇 *Windows* 類型的主機。

SnapCenter Server 新增主機，然後安裝適用於 Windows 的插件（如果主機上尚未安裝）。



 a| 
主機名稱
 a| 
輸入主機的完全限定網域名稱 (FQDN) 或 IP 位址。

SnapCenter依賴 DNS 的正確配置。因此，最佳做法是輸入完全限定網域名稱 (FQDN)。

您可以輸入以下之一的 IP 位址或 FQDN：

** 獨立主機
** Windows Server 故障轉移叢集 (WSFC)
+
如果您使用SnapCenter新增主機且它是子網域的一部分，則必須提供 FQDN。





 a| 
證書
 a| 
選擇您建立的憑證名稱或建立新的憑證。

該憑證必須具有遠端主機的管理權限。有關詳細信息，請參閱有關建立憑證的資訊。

將遊標放在您提供的憑證名稱上即可顯示有關憑證的詳細信息，包括使用者名稱、網域和主機類型。


NOTE: 驗證模式由您在新增主機精靈中指定的主機類型決定。

|===
. 在選擇要安裝的插件部分中，選擇要安裝的插件。
+
對於新部署，沒有列出插件包。

. （可選）按一下“更多選項”。
+
|===
| 對於這個領域... | 這樣做... 


 a| 
港口
 a| 
保留預設連接埠號碼或指定連接埠號碼。

預設連接埠號碼為 8145。如果SnapCenter伺服器安裝在自訂連接埠上，則該連接埠號碼將顯示為預設連接埠。


NOTE: 如果您手動安裝了插件並指定了自訂端口，則必須指定相同的端口。否則，操作失敗。



 a| 
安裝路徑
 a| 
預設路徑為 C:\Program Files\ NetApp\ SnapCenter。

您可以選擇自訂路徑。對於適用於 Windows 的SnapCenter插件包，預設路徑為 C:\Program Files\ NetApp\ SnapCenter。但是，如果您願意，您可以自訂預設路徑。



 a| 
新增叢集中的所有主機
 a| 
選取此複選框可新增 WSFC 中的所有叢集節點。



 a| 
跳過預安裝檢查
 a| 
如果您已經手動安裝了插件並且不想驗證主機是否符合安裝插件的要求，請選取此核取方塊。



 a| 
使用群組託管服務帳戶 (gMSA) 執行外掛程式服務
 a| 
如果要使用群組託管服務帳戶 (gMSA) 來執行外掛程式服務，請選取此核取方塊。

以以下格式提供 gMSA 名稱：_domainName\accountName$_。


NOTE: gMSA 將僅用作 Windows 服務的SnapCenter插件的登入服務帳戶。

|===
. 點選“*提交*”。
+
如果您未選取「跳過預先檢查」複選框，則會驗證主機是否符合安裝插件的要求。系統會根據最低要求驗證磁碟空間、RAM、PowerShell 版本、.NET 版本和位置。如果不符合最低要求，則會顯示相應的錯誤或警告訊息。

+
如果錯誤與磁碟空間或 RAM 有關，您可以更新位於 `C:\Program Files\NetApp\SnapCenter`WebApp 修改預設值。如果錯誤與其他參數有關，則必須修復該問題。

+

NOTE: 在 HA 設定中，如果您要更新 web.config 文件，則必須在兩個節點上更新該文件。

. 監控安裝進度。

