---
sidebar: sidebar 
permalink: sc-automation/concept_rest_web_services_foundation.html 
keywords: uri endpoints, http messages, json format 
summary: REST 是一種建立分散式 Web 應用程式的風格。當應用於 Web 服務 API 的設計時，它可以建立一套用於公開基於伺服器的資源並管理其狀態的技術和最佳實踐。它採用主流協議和標準，為管理SnapCenter提供靈活的基礎。 
---
= REST Web 服務基礎
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
表述性狀態傳輸 (REST) 是一種用於建立分散式 Web 應用程式的樣式。當應用於 Web 服務 API 的設計時，它可以建立一套用於公開基於伺服器的資源並管理其狀態的技術和最佳實踐。它採用主流協議和標準，為管理SnapCenter提供靈活的基礎。



== 資源和國家代表

資源是基於 Web 系統的基本元件。在建立 REST Web 服務應用程式時，早期設計任務包括：



=== 識別系統或基於伺服器的資源

每個系統都會使用和維護資源。資源可以是文件、業務事務、流程或管理實體。基於 REST Web 服務設計應用程式的首要任務之一就是識別資源。



=== 資源狀態和相關狀態操作的定義

資源總是處於有限數量的狀態之一。應該明確定義狀態以及用於影響狀態變化的相關操作。



== URI 端點

每個 REST 資源都必須使用定義明確的尋址方案進行定義和提供。資源所在和識別的端點使用統一資源標識符 (URI)。 URI

提供了一個通用框架，用於為網路中的每個資源建立唯一名稱。統一資源定位符 (URL) 是一種用於 Web 服務識別和存取資源的 URI。資源通常以類似文件目錄的層級結構公開。



== HTTP 郵件

超文本傳輸協定 (HTTP) 是 Web 服務用戶端和伺服器用來交換資源請求和回應訊息的協定。

作為設計 Web 服務應用程式的一部分，HTTP 方法被對應到資源和對應的狀態管理作業。HTTP 是無狀態的。因此，要將一組相關的請求和回應關聯為一個交易的一部分，必須在請求和回應資料流攜帶的 HTTP 標頭中包含附加資訊。



== JSON 格式

雖然可以透過多種方式在 Web 服務用戶端和伺服器之間建置和傳輸訊息，但最受歡迎的選項是 JavaScript 物件表示法 (JSON)。

是一種行業標準，用於以純文字表示簡單資料結構，並用於傳輸描述資源的狀態資訊。SnapCenter REST API 使用 JSON 來格式化每個 HTTP 請求和回應主體中攜帶的資料。
