---
sidebar: sidebar 
permalink: sc-automation/concept_input_variables_controlling_an_api_request.html 
keywords: http methods, request headers, request body, filtering objects, size, pagination 
summary: 您可以透過 HTTP 請求中設定的參數和變數來控制如何處理 API 呼叫。 
---
= 控制 API 請求的輸入變數
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以透過 HTTP 請求中設定的參數和變數來控制如何處理 API 呼叫。



== HTTP 方法

SnapCenter REST API 支援的 HTTP 方法如下表所示。


NOTE: 並非所有 HTTP 方法在每個 REST 端點上都可用。

|===
| HTTP 方法 | 描述 


| 得到 | 檢索資源實例或集合上的物件屬性。 


| 郵政 | 根據提供的輸入建立一個新的資源實例。 


| 刪除 | 刪除現有的資源實例。 


| 放 | 修改現有的資源實例。 
|===


== 請求標頭

您應該在 HTTP 請求中包含幾個標頭。



=== 內容類型

如果請求主體包含 JSON，則此標頭應設定為 _application/json_。



=== 接受

此標頭應設定為 _application/json_。



=== 授權

應設定基本身份驗證，將使用者名稱和密碼編碼為 base64 字串。



== 請求正文

請求主體的內容根據具體呼叫而有所不同。 HTTP請求主體由以下之一組成：

* 帶有輸入變數的 JSON 對象
* 空的




== 篩選對象

發出使用 GET 的 API 呼叫時，您可以根據任意屬性限製或過濾傳回的物件。例如，您可以指定要符合的精確值：

`<field>=<query value>`

除了精確匹配之外，還可以使用其他運算子來傳回一系列值上的物件。  SnapCenter REST API 支援下表所示的篩選運算子。

|===
| 操作員 | 描述 


| = | 等於 


| < | 少於 


| > | 大於 


| <= | 小於或等於 


| >= | 大於或等於 


| 更新 | 或者 


| ！ | 不等於 


| * | 貪婪通配符 
|===
您也可以透過使用 *null* 關鍵字或其否定 *!null* 作為查詢的一部分，根據特定欄位是否設定來傳回物件集合。


NOTE: 任何未設定的欄位通常都會被排除在符合查詢之外。



== 請求特定物件字段

預設情況下，使用 GET 發出 API 呼叫僅傳回唯一標識一個或多個物件的屬性。這組最小欄位將充當每個物件的鍵，並根據物件類型而有所不同。您可以使用 `fields`查詢參數有以下幾種方式：



=== 通用或標準字段

指定 *fields=** 來檢索最常用的物件欄位。這些欄位通常保存在本機伺服器記憶體中或幾乎不需要處理即可存取。這些是使用帶有 URL 路徑鍵（UUID）的 GET 後為物件返回的相同屬性。



=== 所有字段

指定 *fields=*** 來檢索所有物件字段，包括那些需要額外的伺服器處理才能存取的字段。



=== 自訂欄位選擇

使用 *fields=<field_name>* 指定您想要的確切欄位。請求多個欄位時，必須使用逗號分隔值，且不能使用空格。


IMPORTANT: 作為最佳實踐，您應該始終識別所需的特定欄位。您應該只在需要時檢索公共欄位集或所有欄位。哪些欄位被歸類為常見欄位並使用 _fields=*_ 返回，由NetApp根據內部效能分析決定。字段的分類在未來的版本中可能會發生變化。



== 對輸出集中的物件進行排序

資源集合中的記錄將按照物件定義的預設順序傳回。您可以使用 `order_by`查詢參數的欄位名稱和排序方向如下：

`order_by=<field name> asc|desc`

例如，您可以按降序對類型欄位進行排序，然後按升序對 id 進行排序：

`order_by=type desc, id asc`

* 如果指定了排序欄位但未提供方向，則值將按升序排序。
* 當包含多個參數時，必須用逗號分隔欄位。




== 檢索集合中的物件時進行分頁

當使用 GET 發出 API 呼叫來存取相同類型的物件集合時， SnapCenter會嘗試根據兩個約束傳回盡可能多的物件。您可以使用請求中的附加查詢參數來控制每個約束。對於特定的 GET 請求，達到的第一個約束將終止該請求，從而限制傳回的記錄數。


NOTE: 如果請求在遍歷所有物件之前結束，則回應包含檢索下一批記錄所需的連結。



=== 限制對象的數量

預設情況下， SnapCenter對於 GET 請求最多傳回 10,000 個物件。您可以使用 _max_records_ 查詢參數來變更此限制。例如：

`max_records=20`

根據相關時間限制以及系統中的物件總數，實際傳回的物件數量可能小於有效的最大值。



=== 限制檢索物件所花費的時間

預設情況下， SnapCenter會在 GET 請求允許的時間內傳回盡可能多的物件。預設超時時間為 15 秒。您可以使用 _return_timeout_ 查詢參數來變更此限制。例如：

`return_timeout=5`

根據物件數量的相關限制以及系統中物件總數，實際傳回的物件數量可能小於有效的最大值。



=== 縮小結果集

如果需要，您可以將這兩個參數與其他查詢參數組合以縮小結果集。例如，以下內容傳回指定時間之後產生的最多 10 個 EMS 事件：

`time=> 2018-04-04T15:41:29.140265Z&max_records=10`

您可以發出多個請求來翻閱物件。每個後續 API 呼叫都應根據最後一個結果集中的最新事件使用新的時間值。



== 尺寸屬性

一些 API 呼叫以及某些查詢參數使用的輸入值是數字。您可以選擇使用後綴，而不是提供以位元組為單位的整數，如下表所示。

|===
| 後綴 | 描述 


| 知識庫 | KB 千字節（1024 位元組）或千比字節 


| MB | MB 兆位元組（KB x 1024 位元組）或兆比位元組 


| 英國 | GB 千兆位元組（MB x 1024 位元組）或吉比位元組 


| 結核病 | TB 太字節 (GB x 1024 位元組) 或太比位元組 


| 鉛 | PB 拍字節 (TB x 1024 位元組) 或 pebibytes 
|===