---
permalink: admin/concept_overview_of_dashboard.html 
sidebar: sidebar 
keywords: dashboard 
summary: '從SnapCenter左側導覽窗格中，儀表板可讓您初步了解系統的運作狀況，包括最近的作業活動、警報、保護摘要、儲存效率和使用情況、 SnapCenter作業的狀態（備份、複製、還原）、獨立和 Windows 叢集主機的設定狀態、 SnapCenter管理的儲存空間 (SVM) 虛擬數量以及授權容量。' 
---
= 儀表板概覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從SnapCenter左側導覽窗格中，儀表板可讓您初步了解系統的運作狀況，包括最近的作業活動、警報、保護摘要、儲存效率和使用情況、 SnapCenter作業的狀態（備份、複製、還原）、獨立和 Windows 叢集主機的設定狀態、 SnapCenter管理的儲存空間 (SVM) 虛擬數量以及授權容量。

儀表板視圖中顯示的資訊取決於指派給目前登入SnapCenter 的使用者的角色。如果使用者沒有權限查看某些訊息，則可能不會顯示該內容。

在許多情況下，您可以將滑鼠懸停在 *i* 上來查看有關顯示器的更多資訊。在某些情況下，儀表板顯示中的信息會連結到SnapCenter GUI 頁面中的詳細來源信息，例如資源、監視器和報告。



== 最近的工作活動

「最近的作業活動」圖塊顯示您有權存取的任何備份、還原和複製作業的最新作業活動。此顯示中的作業具有以下狀態之一：已完成、警告、失敗、正在執行、排隊和已取消。

將滑鼠懸停在某個工作上可以提供更多資訊。您可以透過點擊特定的作業編號來查看其他作業訊息，該編號會將您重新導向到「監視」頁面。從那裡，您可以獲得作業詳細資訊或日誌信息，並產生特定於該作業的報告。

按一下「查看全部」以查看所有SnapCenter作業的歷史記錄。



== 警報

警報磁貼顯示主機和SnapCenter伺服器的最新未解決的嚴重和警告警報。

嚴重和警告類別警報的總數顯示在顯示器頂部。點擊「嚴重」或「警告」總數會將您重新導向到「警報」頁面，並在「警報」頁面中套用特定的過濾器。

點擊特定警報會將您重定向到「警報」頁面，以查看有關該警報的詳細資訊。點擊顯示器底部的「查看全部」會將您重新導向到「警報」頁面，以查看所有警報的清單。



== 最新保護摘要

最新保護摘要圖塊為您提供您有權存取的所有實體的保護狀態。預設情況下，顯示設定為提供所有插件的狀態。提供以快照形式備份到主儲存的資源以及使用SnapMirror和SnapVault技術備份到二級儲存的資源的狀態資訊。二級儲存的保護狀態資訊的可用性取決於所選的插件類型。


NOTE: 如果您使用鏡像保管庫保護策略，則保護摘要的計數器將顯示在SnapVault摘要圖表中，而不是SnapMirror圖表中。

透過從下拉式選單中選擇插件，可以查看單一插件的保護狀態。環形圖顯示所選插件的受保護資源百分比。點擊環形圖切片會將您重新導向到「報表」>「外掛」頁面，該頁面提供指定外掛程式所有主儲存和二級儲存活動的詳細報告。


IMPORTANT: 有關二級儲存的報告僅適用於SnapVault ；不支援SnapMirror報告。


NOTE: SAP HANA 為快照的主儲存和輔助儲存提供保護狀態資訊。對於基於檔案的備份，僅主儲存保護狀態可用。

|===
| 保護狀態 | 主儲存 | 二級儲存 


 a| 
失敗的
 a| 
屬於資源組的實體的數量，其中資源組已執行備份，但備份失敗。
 a| 
備份未能傳輸至輔助目標的實體數量。



 a| 
成功的
 a| 
資源組中已成功備份的實體的數量。
 a| 
已成功傳輸到輔助目標的具有備份的實體的數量。



 a| 
未配置
 a| 
不屬於任何資源組且尚未備份的實體的數量。
 a| 
屬於一個或多個資源組且未配置為將備份傳送到輔助目標的實體的​​數量。



 a| 
未發起
 a| 
屬於資源組但尚未執行備份的實體的數量。
 a| 
不適用。

|===

NOTE: 如果您使用SnapCenter Server 4.2 和早期版本的插件（早於 4.2）來建立備份，則 *最新保護摘要* 圖塊不會顯示這些備份的SnapMirror保護狀態。



== 工作

作業磁貼為您提供了您有權存取的備份、還原和複製作業的摘要。您可以使用下拉式選單自訂任何報告的時間範圍。時間範圍選項固定為過去 24 小時、過去 7 天和過去 30 天。預設報告顯示過去 7 天內執行的資料保護作業。

備份、復原和複製作業資訊顯示在環形圖中。點擊甜甜圈切片會將您重新導向到「監視」頁面，其中作業過濾器已預先套用至選擇。

|===
| 作業狀態 | 描述 


 a| 
失敗的
 a| 
失敗的作業數量。



 a| 
警告
 a| 
遇到錯誤的作業數量。



 a| 
成功的
 a| 
已成功完成的作業數量。



 a| 
跑步
 a| 
目前正在運行的作業數量。

|===


== 儲存

存儲磁貼顯示 90 天內保護作業所消耗的主存儲和輔助存儲，以圖形方式描繪消耗趨勢，併計算主存儲節省量。儲存資訊每24小時凌晨12點更新一次

當天的消耗總量（包括SnapCenter中可用的備份總數以及這些備份佔用的大小）將顯示在顯示器頂部。一個備份可以有多個與之關聯的快照，並且計數將反映相同的情況。這適用於主快照和次快照。例如，您建立了 10 個備份，其中 2 個由於基於策略的備份保留而被刪除，1 個備份被您明確刪除。因此，將顯示 7 個備份的數量以及這 7 個備份所佔用的大小。

主儲存的儲存節省係數是邏輯容量（複製和快照節省加上消耗的儲存）與主儲存的實體容量的比率。長條圖顯示了儲存節省情況。

此折線圖分別繪製了連續 90 天期間每天的主儲存和二級儲存消耗。將滑鼠懸停在圖表上即可查看每日的詳細結果。


NOTE: 如果您使用SnapCenter Server 4.2 和早期版本的插件（早於 4.2）來建立備份，則 *儲存* 圖塊不會顯示備份數量、這些備份消耗的儲存空間、快照節省、複製節省和快照大小。



== 配置

設定磁貼提供SnapCenter正在管理且您有權存取的所有活動獨立主機和 Windows 叢集主機的綜合狀態資訊。這包括與這些主機相關的插件狀態資訊。

點擊「主機」旁邊的數字會將您重新導向到「主機」頁面中的「託管主機」部分。從那裡，您可以獲得所選主機的詳細資訊。

此外，此顯示還顯示了SnapCenter正在管理且您有權存取的獨立ONTAP SVM 和叢集ONTAP SVM 的總和。點擊 SVM 旁邊的數字會將您重新導向到「儲存系統」頁面。從那裡，您可以獲得所選 SVM 的詳細資訊。

主機配置狀態顯示為紅色（嚴重）、黃色（警告）和綠色（活動），以及每種狀態的主機數量。為每個狀態提供狀態訊息。

|===
| 配置狀態 | 描述 


 a| 
強制升級
 a| 
運行不支援的插件且需要升級的主機數量。不受支援的插件與此版本的SnapCenter不相容。



 a| 
強制遷移
 a| 
運行不支援的插件且需要遷移的主機數量。不受支援的插件與此版本的SnapCenter不相容。



 a| 
未安裝任何插件
 a| 
新增成功但需要安裝插件或插件安裝失敗的主機數量。



 a| 
暫停
 a| 
計劃暫停和正在維護的主機數量。



 a| 
已停止
 a| 
已啟動但插件服務未運行的主機數量。



 a| 
主機宕機
 a| 
已關閉或無法存取的主機數量。



 a| 
可升級（可選）
 a| 
可升級新版本插件包的主機數量。



 a| 
可遷移（可選）
 a| 
可供遷移較新版本插件的主機數量。



 a| 
配置日誌目錄
 a| 
必須配置日誌目錄以便 SCSQL 進行交易日誌備份的主機數量。



 a| 
配置 VMware 插件
 a| 
需要新增適用SnapCenter Plug-in for VMware vSphere的主機數量。



 a| 
未知
 a| 
已註冊但尚未觸發安裝的主機數量。



 a| 
跑步
 a| 
已啟動且正在執行插件的主機數量。對於 SCSQL 插件，需要設定日誌目錄和虛擬機器管理程式。



 a| 
安裝\解除安裝插件
 a| 
正在進行插件安裝或卸載的主機數量。

|===