---
permalink: admin/concept_manage_policies.html 
sidebar: sidebar 
keywords: Manage policies 
summary: 您可以從資源或資源群組中分離策略，並進行修改、刪除、檢視和複製。 
---
= 管理政策
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從資源或資源群組中分離策略，並進行修改、刪除、檢視和複製。



== 修改策略

當策略附加到資源或資源組時，您可以修改複製選項、快照保留設定、錯誤重試計數或腳本資訊。只有在分離策略後，您才可以修改計劃類型（頻率）。

*關於此任務*

修改政策中的計劃類型需要額外的步驟，因為SnapCenter伺服器僅在將政策附加到資源或資源群組時註冊計劃類型。

|===
| 如果你想... | 然後... 


 a| 
新增額外的計劃類型
 a| 
建立新策略並將其附加到必要的資源或資源群組。

例如，如果資源組策略僅指定每小時備份，而您也想新增每日備份，則可以建立具有每日排程類型的策略並將其新增至資源組。資源組將有兩個策略：每小時和每天。



 a| 
刪除或變更計劃類型
 a| 
執行以下操作：

. 將該策略與使用該策略的每個資源和資源群組分開。
. 修改排程類型。
. 將該策略重新附加到所有資源和資源群組。


例如，如果某個策略指定每小時備份，而您想要將其變更為每日備份，則必須先分開該策略。

|===
*步驟*

. 在左側導覽窗格中，按一下「*設定*」。
. 在「設定」頁面中，按一下「*策略*」。
. 選擇策略，然後按一下「修改」。
. 修改訊息，然後按一下「完成」。




== 分離策略

如果您不再希望策略來管理資源的資料保護，則可以隨時從資源或資源群組中分離這些策略。您必須先分離策略，然後才能刪除它或修改計劃類型。

*步驟*

. 在左側導覽窗格中，按一下“*資源*”，然後從清單中選擇適當的外掛程式。
. 在資源頁面中，從*視圖*清單中選擇*資源組*。
. 選擇資源組，然後按一下「修改資源組」。
. 在修改資源組精靈的政策頁面中，從下拉清單中清除要分離的策略旁的複選標記。
. 在精靈的其餘部分對資源組進行任何其他修改，然後按一下「完成」。




== 刪除策略

如果您不再需要策略，您可能需要刪除它們。

.開始之前
如果策略與任何資源或資源組關聯，則應將策略與資源或資源組分開。

*步驟*

. 在左側導覽窗格中，按一下「*設定*」。
. 在「設定」頁面中，按一下「*策略*」。
. 選擇該策略，然後按一下“*刪除*”。
. 按一下“是”。

