---
permalink: admin/concept_overview_of_snapcenter_reports.html 
sidebar: sidebar 
keywords: SnapCenter reports 
summary: SnapCenter提供多種報告選項，使您能夠監控和管理系統健康和操作成功。 
---
= SnapCenter報告功能概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter提供多種報告選項，使您能夠監控和管理系統健康和操作成功。

|===
| 報告類型 | 描述 


 a| 
備份報告
 a| 
備份報告提供有關SnapCenter環境的備份趨勢的整體資料、備份成功率以及有關在指定時間內執行的每個備份的一些資訊。如果刪除了備份，則報告不會顯示已刪除備份的任何狀態資訊。備份詳細報告提供有關指定備份作業的詳細信息，並列出成功備份的資源和失敗的資源。



 a| 
克隆報告
 a| 
克隆報告提供有關SnapCenter環境的克隆趨勢的總體數據、克隆成功率以及有關在指定時間內執行的每個克隆作業的一些資訊。如果刪除了克隆，則報告不會顯示已刪除克隆的任何狀態資訊。複製詳細報告提供指定複製、複製主機和複製作業任務狀態的詳細資訊。如果任務失敗，複製詳細報告將顯示有關失敗的資訊。



 a| 
恢復報告
 a| 
恢復報告提供有關恢復作業的總體資訊。恢復詳細資訊報告提供有關指定恢復作業的詳細信息，包括主機名稱、備份名稱、作業開始和持續時間以及各個作業任務的狀態。如果任務失敗，恢復詳細報告將顯示有關失敗的資訊。



 a| 
保護報告
 a| 
這些報告提供所有SnapCenter插件執行個體管理的資源的保護詳細資訊。此報告提供所有插件實例管理的資源的保護詳細資訊。您可以查看概覽、未受保護資源的詳細資訊、產生報告時尚未備份的資源、備份作業失敗的資源組的資源以及SnapVault狀態。



 a| 
定期報告
 a| 
這些報告計劃定期運行，例如每天、每週或每月。報告會在指定的日期和時間自動生成，並透過電子郵件發送給相關人員。您可以啟用、停用、修改或刪除計畫。透過點選「立即執行」按鈕，可以按需執行已啟用的計畫。管理員可以執行任何計劃，但產生的報告將包含基於建立該計劃的使用者提供的權限的資料。

除管理員之外的任何其他使用者都可以根據其權限查看或修改計劃。如果在新增角色頁面中選擇了該角色的所有成員都可以看到其他成員的物件選項，則該角色的其他成員將能夠檢視和修改。

|===


== 訪問報告

您可以使用SnapCenter儀表板快速了解系統健康狀況。您可以從儀表板深入了解更多詳細資訊。或者，您可以直接存取詳細報告。

您可以透過以下方法之一存取報告：

* 在左側導覽窗格中，按一下“*儀表板*”，然後按一下“*上次保護摘要*”圓餅圖以在“報表”頁面中查看更多詳細資訊。
* 在左側導覽窗格中，按一下「*報告*」。




== 過濾報告

您可能希望根據所需資訊的詳細程度和時間跨度，按照一系列參數來篩選報告資料。

*步驟*

. 在左側導覽窗格中，按一下「*報告*」。
. 如果未顯示參數視圖，請按一下報表工具列中的「*切換參數區域*」圖示。
. 指定您想要執行報表的時間範圍。  + 如果省略結束日期，您將檢索所有可用資訊。
. 根據以下任一條件過濾報告資訊：
+
** 資源組
** 主持人
** 政策
** 資源
** 地位
** 插件名稱


. 按一下“*應用*”。




== 匯出或列印報告

匯出SnapCenter報告可讓您以多種其他格式查看報告。您也可以列印報告。

*步驟*

. 在左側導覽窗格中，按一下「*報告*」。
. 從報告工具列中執行以下操作之一：
+
** 按一下「切換列印預覽」圖示即可預覽可列印的報告。
** 從*匯出*圖示下拉清單中選擇一種格式，將報告匯出為其他格式。


. 若要列印報告，請按一下「*列印*」圖示。
. 若要查看特定的報告摘要，請捲動至報告的相應部分。




== 設定電子郵件通知的 SMTP 伺服器

您可以指定用於向自己或其他人傳送資料保護作業報告的 SMTP 伺服器。您也可以傳送測試電子郵件來驗證配置。這些設定將全域套用至您設定電子郵件通知的任何SnapCenter作業。

此選項配置 SMTP 伺服器以傳送所有資料保護作業報告。但是，如果您希望定期將特定資源的SnapCenter資料保護作業更新傳送給您自己或其他人，以便您可以監控這些更新的狀態，則可以在建立資源群組時配置透過電子郵件傳送SnapCenter報表的選項。

*步驟*

. 在左側導覽窗格中，按一下「*設定*」。
. 在設定頁面中，按一下*全域設定*。
. 輸入 SMTP 伺服器並點擊 *儲存*。
. 若要傳送測試電子郵件，請輸入您要傳送電子郵件的電子郵件地址，輸入主題，然後按一下「*傳送*」。




== 配置透過電子郵件傳送報告的選項

如果您希望定期將SnapCenter資料保護作業更新傳送給自己或其他人，以便您可以監視這些更新的狀態，您可以在建立資源群組時配置透過電子郵件傳送SnapCenter報表的選項。

.開始之前
您必須在「設定」下的「全域設定」頁面中設定您的 SMTP 伺服器。

*步驟*

. 在左側導覽窗格中，按一下“*資源*”，然後從清單中選擇適當的外掛程式。
. 選擇您要檢視的資源類型並點選*新資源群組*，或選擇現有的資源群組並點選*修改*為現有資源群組設定電子郵件報表。
. 在新資源組精靈的通知面板中，從下拉式選單中選擇是否始終接收報告、在失敗時接收報告、在失敗或警告時接收報告。
. 輸入電子郵件的寄件地址、收件者地址以及電子郵件的主題。

