---
permalink: admin/concept_monitor_jobs_schedules_events_and_logs.html 
sidebar: sidebar 
keywords: Monitor jobs, schedules, events, logs 
summary: 您可以從「監視」頁面監視作業的進度、取得有關排程作業的資訊以及查看事件和日誌。 
---
= 監控作業、計畫、事件和日誌
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從「監視」頁面監視作業的進度、取得有關排程作業的資訊以及查看事件和日誌。



== 監控作業

您可以查看有關SnapCenter備份、複製、還原和驗證作業的資訊。您可以根據開始和結束日期、作業類型、資源群組、政策或SnapCenter插件來篩選此視圖。您還可以獲得指定作業的其他詳細資訊和日誌檔案。

您也可以監控與SnapMirror和SnapVault作業相關的作業。


NOTE: 除非您被指派了SnapCenter管理員或其他超級使用者角色，否則您只能監控您建立的與您相關的作業。

您可以執行以下與監控作業相關的任務：

* 監控備份、複製、復原和驗證作業。
* 查看作業詳細資訊和報告。
* 停止預定的作業。




=== 管理計畫的備份作業

從SnapCenter 6.0.1 版本開始，引入了一個新參數 *JobConcurrencyThreshold*，它為可在任何給定時間運行的計劃作業數量設定閾值。這可讓您根據系統硬體配置控制要執行的備份次數。

指派給 *JobConcurrencyThreshold* 的預設值為 0，即停用。如果您在計劃的備份視窗期間觀察到效能下降，則可以透過指派值來啟用。


NOTE: 如果您啟用 *JobConcurrencyThreshold* 來管理並發作業， SnapCenter將不允許您控制備份的順序，且備份可能不會在計畫中指定的時間同時觸發。

.步驟
. 設定位於 _C:\Program Files\ NetApp\ SnapCenter WebApp\ SnapManager.Web.UI.dll.config_ 的 _JobConcurrencyThreshold_ 參數的值。
. 透過點選 IIS > 應用程式集區 > SnapCenter > 重新啟動來回收SnapCenter應用程式集區。
. 點選 IIS > 網站 > SnapCenter > 重新啟動，重新啟動SnapCenter Web 服務。




=== 管理過時的作業

陳舊的作業是由於SnapCenter中斷或不正確的作業更新而創建的。從SnapCenter 6.0.1 版本開始，引入了預先定義的計劃來清理這些停滯超過 72 小時的陳舊作業。您可以透過編輯可設定參數 *CleanUpStaleJobsIntervalHours* 來變更計劃頻率。

您可以從 *Monitor* > *Schedules* > *SnapCenter_StaleJobCleanUp* 執行計畫來按需觸發清理。

.步驟
. 設定位於 _C:\Program Files\ NetApp\ SnapCenter WebApp\ SnapManager.Web.UI.dll.config_ 的 _CleanUpStaleJobsIntervalHours_ 參數的值。
. 透過點選 IIS > 應用程式集區 > SnapCenter > 重新啟動來回收SnapCenter應用程式集區。
. 點選 IIS > 網站 > SnapCenter > 重新啟動，重新啟動SnapCenter Web 服務。




== 監控時間表

您可能想要查看當前計劃以確定操作何時開始、上次運行的時間以及下次運行的時間。您也可以確定執行該操作的主機，以及該操作的資源群組和政策資訊。

*步驟*

. 在左側導覽窗格中，按一下「*監控*」。
. 在監控頁面中，按一下*計劃*。
. 選擇資源組和計劃類型。
. 查看已排程的操作清單。




== 監視事件

您可以查看系統中的SnapCenter事件列表，例如使用者建立資源群組時或系統啟動活動時（例如建立排程備份）。您可能想要查看事件以確定備份或還原作業等作業目前是否正在進行中。

*關於此任務*

所有工作資訊都會顯示在「事件」頁面中。例如，當備份作業開始時，就會出現「備份開始」事件。當備份完成時，會出現「備份完成」事件。

*步驟*

. 在左側導覽窗格中，按一下「*監控*」。
. 在「監控」頁面中，按一下「*事件*」。
. （可選）在過濾器框中，輸入開始或結束日期、事件類別（例如備份、資源組或策略）和嚴重性級別，然後按一下*套用*。或者，在搜尋框中輸入字元。
. 查看事件清單。




== 監控日誌

您可以檢視和下載SnapCenter伺服器日誌、 SnapCenter主機代理程式日誌和插件日誌。您可能希望查看日誌以協助進行故障排除。

*關於此任務*

您可以過濾日誌以僅顯示特定的日誌嚴重性等級：

* 偵錯
* 資訊
* 警告
* 錯誤
* 致命的


您也可以取得作業等級日誌，例如協助您排除備份作業失敗原因的日誌。對於作業等級日誌，請使用 *Monitor* > *Jobs* 選項。

*步驟*

. 在左側導覽窗格中，按一下「*監控*」。
. 在「作業」頁面中，選擇一個作業並按一下「下載日誌」。
+
下載的壓縮資料夾包含作業日誌和公用日誌。壓縮資料夾名稱包含所選的作業 ID 和作業類型。

. 在「監控」頁面中，按一下「*日誌*」。
. 選擇日誌類型、主機和實例。
+
如果將日誌類型選擇為“*插件*”，則可以選擇主機或SnapCenter插件。如果日誌類型為“伺服器*”，則無法執行此操作。

. 若要按特定來源、訊息或日誌等級過濾日誌，請按一下列標題頂部的篩選器圖示。
+
若要顯示所有日誌，請選擇*大於或等於*作為 `Debug`等級。

. 按一下“*刷新*”。
. 查看日誌列表。
. 按一下“*下載*”下載日誌。
+
下載的壓縮資料夾包含作業日誌和公用日誌。壓縮資料夾名稱包含所選的作業 ID 和作業類型。



在大型配置中，為了獲得最佳效能，您應該使用 PowerShell cmdlet 將SnapCenter的日誌設定設為最低等級。

`Set-SmLogSettings -LogLevel All -MaxFileSize 10MB -MaxSizeRollBackups 10 -JobLogsMaxFileSize 10MB -Server`


NOTE: 若要在故障轉移作業完成後存取運作狀況或設定信息，請執行 cmdlet `Get-SmRepositoryConfig` 。



== 從SnapCenter中刪除作業和日誌

您可以從SnapCenter中刪除備份、還原、複製和驗證作業和日誌。 SnapCenter會無限期地儲存成功和失敗的作業日誌，除非您將其刪除。您可能想要移除它們以補充儲存空間。

*關於此任務*

目前一定沒有正在運行的作業。您可以透過提供作業 ID 來刪除特定作業，也可以在指定時間內刪除作業。

您不需要將主機置於維護模式來刪除作業。

*步驟*

. 啟動 PowerShell。
. 在命令提示字元下輸入： `Open-SMConnection`
. 在命令提示字元下輸入： `Remove-SmJobs`
. 在左側導覽窗格中，按一下「*監控*」。
. 在「監控」頁面中，按一下「作業」。
. 在「作業」頁面中，檢視作業的狀態。


.相關資訊
可以透過執行_Get-Help command_name_來取得有關可與 cmdlet 一起使用的參數及其描述的資訊。或者，您也可以參考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter軟體 Cmdlet 參考指南"^]。
