---
permalink: admin/task_manage_resource_groups.html 
sidebar: sidebar 
keywords: Manage resource groups 
summary: 您可以對資源組執行各種操作。 
---
= 管理資源組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以對資源組執行各種操作。

您可以執行與資源組相關的下列任務：

* 透過選擇資源組並按一下「修改資源組」來修改資源組，以編輯您在建立資源組時提供的資訊。
+

NOTE: 您可以在修改資源組的同時變更計劃。但是，要變更計劃類型，您必須修改策略。

+

NOTE: 如果從資源群組中刪除資源，則目前附加到資源群組的政策中定義的備份保留設定將繼續套用於已刪除的資源。

* 建立資源組的備份。
* 建立備份的克隆。
+
您可以從 SQL、Oracle、Windows 檔案系統、自訂應用程式和 SAP HANA 資料庫資源或資源群組的現有備份中進行複製。

* 建立資源組的克隆。
+
此操作僅支援 SQL 資源組（僅包含資料庫）。您可以設定複製資源群組的計畫（複製生命週期）。

* 阻止資源組上的預定操作啟動。
* 刪除資源組。




== 停止和恢復資源組的操作

您可以暫時禁止在資源組上啟動計劃操作。稍後當您需要時，您可以啟用這些操作。

*步驟*

. 在左側導覽窗格中，按一下“*資源*”，然後從清單中選擇適當的外掛程式。
. 在資源頁面中，從*視圖*清單中選擇*資源組*。
. 選擇資源組並點選*維護*。
. 按一下“*確定*”。


如果要還原已置於維護模式的資源組的操作，請選擇該資源組並按一下「生產」。



== 刪除資源組

如果不再需要保護資源組中的資源，則可以刪除該資源組。您必須確保在從SnapCenter中刪除插件之前刪除資源組。

*關於此任務*

您應該手動刪除為資源組中的任何資源建立的所有克隆。您可以選擇強制刪除與資源組相關的所有備份、元資料、政策和快照。

*步驟*

. 在左側導覽窗格中，按一下“*資源*”，然後從清單中選擇適當的外掛程式。
. 在資源頁面中，從*視圖*清單中選擇*資源組*。
. 選擇資源組，然後按一下“*刪除*”。
. 選用：勾選「刪除備份並分離與此資源組關聯的策略」複選框以刪除與該資源組關聯的所有備份、元資料、政策和快照。
. 按一下“*確定*”。

