---
permalink: install/concept_create_and_manage_smb_shares.html 
sidebar: sidebar 
keywords: SMB shares 
summary: '若要在儲存虛擬機器 (SVM) 上設定 SMB3 共用，您可以使用SnapCenter使用者介面或 PowerShell cmdlet。' 
---
= 建立和管理 SMB 共享
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在儲存虛擬機器 (SVM) 上設定 SMB3 共用，您可以使用SnapCenter使用者介面或 PowerShell cmdlet。

|===


| *最佳實踐：*建議使用 cmdlet，因為它使您能夠利用SnapCenter提供的範本來自動化共享配置。 
|===
模板概括了磁碟區和共享配置的最佳實踐。您可以在 Windows 版SnapCenter插件包的安裝資料夾中的 Templates 資料夾中找到這些範本。


TIP: 如果您願意，您可以按照提供的模型建立自己的模板。在建立自訂範本之前，您應該查看 cmdlet 文件中的參數。



== 建立 SMB 共享

您可以使用SnapCenter共用頁面在儲存虛擬機器 (SVM) 上建立 SMB3 共用。

您不能使用SnapCenter備份 SMB 共用上的資料庫。  SMB 支援僅限於設定。

*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*共享*」。
. 從「儲存虛擬機器」下拉清單中選擇 SVM。
. 點選“*新建*”。
+
“新共享”對話方塊開啟。

. 在新共享對話方塊中，定義共享：
+
|===
| 在這個領域... | 這樣做... 


 a| 
描述
 a| 
輸入共享的描述性文字。



 a| 
共享名稱
 a| 
輸入共享名稱，例如 test_share。

您輸入的共享名稱也將用作磁碟區名稱。

共享名稱：

** 必須是 UTF-8 字串。
** 不得包含以下字符：從 0x00 到 0x1F（含）的控製字符、0x22（雙引號）以及特殊字符 `\ / [ ] : (vertical bar) < > + = ; , ?`




 a| 
分享路徑
 a| 
** 按一下該欄位以輸入新的檔案系統路徑，例如 /。
** 雙擊該欄位以從現有檔案系統路徑清單中進行選擇。


|===
. 如果您對輸入的內容滿意，請按一下「*確定*」。
+
SnapCenter在 SVM 上建立 SMB 共用。





== 刪除 SMB 共享

當您不再需要 SMB 共用時，可以將其刪除。

*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*共享*」。
. 在共用頁面中，按一下「*儲存虛擬機器*」欄位以顯示下拉式選單，其中包含可用儲存虛擬機器 (SVM) 的列表，然後選擇要刪除的共用的 SVM。
. 從 SVM 上的共享清單中，選擇要刪除的共享，然後按一下「*刪除*」。
. 在「刪除共享」對話方塊中，按一下「確定」。
+
SnapCenter從 SVM 中刪除 SMB 共用。


