---
permalink: install/configure_ca_certificate_linux_host.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate, linux, linux host 
summary: 您應該在 Linux 主機上使用SnapCenter Server 設定 CA 憑證。 
---
= 為Linux主機設定CA憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 Linux 上安裝SnapCenter伺服器後，安裝程式會建立自簽名憑證。如果要使用 CA 證書，則應為 nginx 反向代理、稽核日誌記錄和SnapCenter服務設定證書。



== 設定nginx證書

.步驟
. 導航至 _/etc/nginx/conf.d_： `cd /etc/nginx/conf.d`
. 使用 vi 或任何文字編輯器開啟 *snapcenter.conf*。
. 導航到設定檔中的伺服器部分。
. 修改_ssl_certificate_和_ssl_certificate_key_的路徑以指向CA憑證。
. 儲存並關閉文件。
. 重新載入 nginx： `$nginx -s reload`




== 配置審核日誌證書

.步驟
. 使用 vi 或任何文字編輯器開啟 _INSTALL_DIR/ NetApp/snapcenter/SnapManagerWeb/ SnapManager。
+
_INSTALL_DIR_ 的預設值是 _/opt_。

. 編輯 *AUDILOG_CERTIFICATE_PATH* 和 *AUDILOG_CERTIFICATE_PASSWORD* 鍵以分別包含 CA 憑證路徑和密碼。
+
稽核日誌憑證僅支援 _.pfx_ 格式。

. 儲存並關閉文件。
. 重新啟動 *snapmanagerweb* 服務： `$ systemctl restart snapmanagerweb`




== 配置SnapCenter服務證書

.步驟
. 使用 vi 或任何文字編輯器開啟以下設定檔。
+
** _INSTALL_DIR/ NetApp/snapcenter/SnapManagerWeb/ SnapManager.Web.UI.dll.config_
** 安裝目錄NetApp
** 安裝目錄NetApp
+
_INSTALL_DIR_ 的預設值是 _/opt_。



. 編輯 *SERVICE_CERTIFICATE_PATH* 和 *SERVICE_CERTIFICATE_PASSWORD* 鍵以分別包含 CA 憑證路徑和密碼。
+
SnapCenter服務憑證僅支援 _.pfx_ 格式。

. 儲存並關閉文件。
. 重新啟動所有服務。
+
** `$ systemctl restart snapmanagerweb`
** `$ systemctl restart smcore`
** `$ systemctl restart scheduler`



