---
permalink: install/create-svm-roles-asa-r2-resources.html 
sidebar: sidebar 
keywords: svm role, privileges, asa r2 systems 
summary: 如果您在ASA r2 系統中設定 SVM 以與 SanpCenter 一起使用且不想使用 vsadmin 角色，則應建立 SVM 角色。 
---
= 為ASA r2 系統建立 SVM 角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須執行幾個ONTAP CLI 命令才能在ASA r2 系統中為新的 SVM 使用者建立角色。如果您在ASA r2 系統中設定 SVM 以與SnapCenter一起使用且不想使用 vsadmin 角色，則需要此角色。

*步驟*

. 在儲存系統上建立一個角色，並為該角色賦予所有權限。
+
`security login role create –vserver <svm_name\>- role <SVM_Role_Name\> -cmddirname <permission\>`

+

NOTE: 您應該對每個權限重複此命令。

. 建立一個使用者並將角色指派給該使用者。
+
`security login create -user <user_name\> -vserver <svm_name\> -application http -authmethod password -role <SVM_Role_Name\>`

. 解除用戶鎖定。
+
`security login unlock -user <user_name\> -vserver <svm_name\>`





== 用於建立 SVM 角色和分配權限的ONTAP CLI 命令

您應該執行幾個ONTAP CLI 命令來建立 SVM 角色並指派權限。

* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "snapmirror list-destinations" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "event generate-autosupport-log" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "job history show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "job show" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "job stop" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "lun" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun delete" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun igroup add" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun igroup create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun igroup delete" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun igroup rename" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun igroup show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun mapping add-reporting-nodes" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "lun mapping create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun mapping delete" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun mapping remove-reporting-nodes" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun mapping show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun modify" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun move-in-volume" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun offline" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun online" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun resize" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun serial" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "lun show" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "network interface" -access readonly`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "snapmirror policy add-rule" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "snapmirror policy modify-rule" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "snapmirror policy remove-rule" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "snapmirror policy show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "snapmirror restore" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "snapmirror show" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "snapmirror show-history" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "snapmirror update" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "snapmirror update-ls-set" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "version" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume clone create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume clone show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume clone split start" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume clone split stop" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume destroy" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume file clone create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume file show-disk-usage" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume modify" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume offline" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume online" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume qtree create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume qtree delete" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume qtree modify" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume qtree show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume restrict" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume snapshot create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume snapshot delete" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume snapshot modify" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "volume snapshot modify-snaplock-expiry-time" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume snapshot rename" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume snapshot restore" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume snapshot restore-file" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume snapshot show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume snapshot show-delta" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume unmount" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver cifs share create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver cifs share delete" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver cifs share show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver cifs show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver export-policy create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver export-policy delete" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver export-policy rule create" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver export-policy rule show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver export-policy show" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "vserver iscsi connection show" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver" -access readonly`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver export-policy" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "vserver iscsi" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "volume clone split status" -access all`
* `security login role create -vserver SVM_name -role SVM_Role_Name -cmddirname "volume managed-feature" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme subsystem map" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme subsystem create" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme subsystem delete" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme subsystem modify" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme subsystem host" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme subsystem controller" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme subsystem show" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme namespace create" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme namespace delete" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme namespace modify" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "nvme namespace show" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "storage-unit show" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "consistency-group" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "snapmirror protect" -access all`
* `security login role create -vserver SVM_Name -role SVM_Role_Name -cmddirname "volume delete" -access all`
* `security login create -user-or-group-name user_name -application http -authentication-method password -role SVM_Role_Name -vserver SVM_Name`
* `security login create -user-or-group-name user_name -application ssh -authentication-method password -role SVM_Role_Name -vserver SVM_Name`

