---
permalink: install/task_create_and_manage_disks.html 
sidebar: sidebar 
keywords: disks, create, manage, clustered disks, view 
summary: Windows 主機將儲存系統上的 LUN 視為虛擬磁碟。您可以使用SnapCenter建立和設定 FC 連線或 iSCSI 連線的 LUN。 
---
= 建立和管理磁碟
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 主機將儲存系統上的 LUN 視為虛擬磁碟。您可以使用SnapCenter建立和設定 FC 連線或 iSCSI 連線的 LUN。

* SnapCenter僅支援基本磁碟。不支援動態磁碟。
* 對於 GPT，只允許一個資料分割區，對於 MBR，只允許一個主分割區，該主分割區具有一個使用 NTFS 或 CSVFS 格式化的磁碟區和一個掛載路徑。
* 支援的分割區樣式：GPT、MBR；在 VMware UEFI VM 中，僅支援 iSCSI 磁碟



NOTE: SnapCenter不支援重新命名磁碟。如果重新命名由SnapCenter管理的磁碟， SnapCenter作業將不會成功。



== 查看主機上的磁碟

您可以使用SnapCenter檢視管理的每個 Windows 主機上的磁碟。

*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*磁碟*」。
. 從*主機*下拉清單中選擇主機。
+
磁碟已列出。





== 查看叢集磁碟

您可以查看使用SnapCenter管理的叢集上的叢集磁碟。僅當您從主機下拉式選單中選擇叢集時才會顯示叢集磁碟。

*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*磁碟*」。
. 從*主機*下拉清單中選擇叢集。
+
磁碟已列出。





== 建立 iSCSI 會話

如果您使用 iSCSI 連線至 LUN，則必須在建立 LUN 之前建立 iSCSI 會話以啟用通訊。

*開始之前*

* 您必須已將儲存系統節點定義為 iSCSI 目標。
* 您必須已經在儲存系統上啟動了 iSCSI 服務。 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["了解更多"^]


*關於此任務*

您只能在相同的 IP 版本之間建立 iSCSI 會話，無論是從 IPv6 到 IPv6，還是從 IPv4 到 IPv4。

只有當主機和目標位於相同子網路中時，才可以使用連結本機 IPv6 位址進行 iSCSI 會話管理以及主機和目標之間的通訊。

如果變更 iSCSI 啟動器的名稱，則對 iSCSI 目標的存取會受到影響。更改名稱後，您可能需要重新配置啟動器存取的目標，以便它們能夠識別新名稱。變更 iSCSI 啟動器的名稱後，必須確保重新啟動主機。

如果您的主機有多個 iSCSI 接口，一旦您使用第一個介面上的 IP 位址建立了與SnapCenter 的iSCSI 會話，您就無法從具有不同 IP 位址的另一個介面建立 iSCSI 會話。

*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*iSCSI 會話*」。
. 從「儲存虛擬機器」下拉清單中，選擇 iSCSI 目標的儲存虛擬機器 (SVM)。
. 從「*主機*」下拉清單中，選擇會話的主機。
. 點選*建立會話*。
+
將顯示「建立會話」精靈。

. 在建立會話精靈中，確定目標：
+
|===
| 在這個領域... | 進入... 


 a| 
目標節點名稱
 a| 
iSCSI 目標的節點名稱

如果存在現有的目標節點名稱，則以唯讀格式顯示該名稱。



 a| 
目標入口網站位址
 a| 
目標網路入口網站的IP位址



 a| 
目標入口網站連接埠
 a| 
目標網路入口網站的TCP端口



 a| 
發起者入口網站位址
 a| 
發起者網路入口網站的 IP 位址

|===
. 當您對輸入的內容滿意時，請按一下「連線」。
+
SnapCenter建立 iSCSI 會話。

. 重複此程序為每個目標建立會話。




== 建立 FC 連線或 iSCSI 連線的 LUN 或磁碟

Windows 主機將儲存系統上的 LUN 視為虛擬磁碟。您可以使用SnapCenter建立和設定 FC 連線或 iSCSI 連線的 LUN。

如果您想在SnapCenter之外建立和格式化磁碟，則僅支援 NTFS 和 CSVFS 檔案系統。

.開始之前
* 您必須已經在儲存系統上為 LUN 建立了一個磁碟區。
+
該磁碟區應該僅保存 LUN，並且僅保存使用SnapCenter建立的 LUN。

+

NOTE: 除非克隆已拆分，否則您無法在SnapCenter建立的複製磁碟區上建立 LUN。

* 您必須已在儲存系統上啟動 FC 或 iSCSI 服務。
* 如果您正在使用 iSCSI，則必須與儲存系統建立 iSCSI 會話。
* 適用於 Windows 的SnapCenter插件包必須僅安裝在要建立磁碟的主機上。


*關於此任務*

* 除非 Windows Server 故障轉移叢集中的主機共用 LUN，否則您無法將 LUN 連線至多個主機。
* 如果使用 CSV（叢集共用磁碟區）的 Windows Server 故障轉移叢集中的主機共用 LUN，則必須在擁有該叢集群組的主機上建立磁碟。


*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*磁碟*」。
. 從*主機*下拉清單中選擇主機。
. 點選“*新建*”。
+
將開啟建立磁碟精靈。

. 在 LUN 名稱頁面中，識別 LUN：
+
|===
| 在這個領域... | 這樣做... 


 a| 
儲存系統
 a| 
選擇 LUN 的 SVM。



 a| 
LUN 路徑
 a| 
按一下「瀏覽」以選擇包含 LUN 的資料夾的完整路徑。



 a| 
LUN 名稱
 a| 
輸入 LUN 的名稱。



 a| 
簇大小
 a| 
選擇叢集的 LUN 區塊分配大小。

叢集大小取決於作業系統和應用程式。



 a| 
LUN 標籤
 a| 
或者，輸入 LUN 的描述性文字。

|===
. 在磁碟類型頁面中，選擇磁碟類型：
+
|===
| 選擇... | 如果... 


 a| 
專用磁碟
 a| 
該 LUN 只能被一個主機存取。

忽略*資源組*欄位。



 a| 
共享磁碟
 a| 
LUN 由 Windows Server 故障轉移叢集中的主機共用。

在「*資源組*」欄位中輸​​入群集資源組的名稱。您只需在故障轉移群集中的一個主機上建立磁碟。



 a| 
叢集共用磁碟區 (CSV)
 a| 
此 LUN 由使用 CSV 的 Windows Server 故障轉移群集中的主機共用。

在「*資源組*」欄位中輸​​入群集資源組的名稱。確保在其上建立磁碟的主機是叢集群組的擁有者。

|===
. 在磁碟機屬性頁面中，指定磁碟機屬性：
+
|===
| 財產 | 描述 


 a| 
自動分配掛載點
 a| 
SnapCenter根據系統磁碟機自動分配磁碟區掛載點。

例如，如果您的系統磁碟機是 C:，則自動指派會在您的 C: 磁碟機下方建立磁碟區裝入點 (C:\scmnpt\)。共享磁碟不支援自動分配。



 a| 
分配磁碟機號
 a| 
將磁碟安裝到您在相鄰下拉清單中選擇的磁碟機。



 a| 
使用卷掛載點
 a| 
將磁碟安裝到您在相鄰欄位中指定的磁碟機路徑。

磁碟區安裝點的根目錄必須由您正在建立磁碟的主機擁有。



 a| 
不要分配磁碟機號或磁碟區安裝點
 a| 
如果您希望在 Windows 中手動安裝磁碟，請選擇此選項。



 a| 
LUN大小
 a| 
指定 LUN 大小；最小 150 MB。

在相鄰的下拉清單中選擇 MB、GB 或 TB。



 a| 
託管此 LUN 的磁碟區使用精簡配置
 a| 
精簡配置 LUN。

精簡配置一次僅分配所需的儲存空間，使 LUN 能夠有效率地成長到最大可用容量。

確保磁碟區上有足夠的可用空間來容納您認為需要的所有 LUN 儲存。



 a| 
選擇分割區類型
 a| 
為 GUID 分割區表選擇 GPT 分割區，或為主開機記錄選擇 MBR 分割區。

MBR 分割區可能會導致 Windows Server 故障轉移叢集中發生錯位問題。


NOTE: 不支援統一可擴充韌體介面 (UEFI) 分割區磁碟。

|===
. 在映射 LUN 頁面中，選擇主機上的 iSCSI 或 FC 啟動器：
+
|===
| 在這個領域... | 這樣做... 


 a| 
主持人
 a| 
雙擊群集組名稱，顯示屬於該群集的主機的下拉列表，然後選擇啟動器的主機。

只有當 LUN 由 Windows Server 故障轉移叢集中的主機共用時，才會顯示此欄位。



 a| 
選擇主機發起者
 a| 
選擇“*光纖通道*”或“*iSCSI*”，然後選擇主機上的啟動器。

如果您使用具有多路徑 I/O (MPIO) 的 FC，則可以選擇多個 FC 啟動器。

|===
. 在「群組類型」頁面中，指定是否要將現有 igroup 對應到 LUN，還是建立新的 igroup：
+
|===
| 選擇... | 如果... 


 a| 
為選定的啟動器建立新的 igroup
 a| 
您想要為選定的啟動器建立一個新的 igroup。



 a| 
為選定的啟動器選擇現有的 igroup 或指定新的 igroup
 a| 
您想要為選定的啟動器指定現有的 igroup，或使用您指定的名稱建立新的 igroup。

在 *igroup name* 欄位中輸入 igroup 名稱。輸入現有 igroup 名稱的前幾個字母以自動完成該欄位。

|===
. 在「摘要」頁面中，檢查您的選擇，然後按一下「完成」。
+
SnapCenter建立 LUN 並將其連接到主機上的指定磁碟機或磁碟機路徑。





== 調整磁碟大小

您可以根據儲存系統需求的變化增加或減少磁碟的大小。

*關於此任務*

* 對於精簡配置的 LUN， ONTAP LUN 幾何大小顯示為最大大小。
* 對於厚置備 LUN，可擴充大小（磁碟區中的可用大小）顯示為最大大小。
* 具有 MBR 樣式分割的 LUN 的大小限制為 2 TB。
* 具有 GPT 樣式分割區的 LUN 的儲存系統大小限制為 16 TB。
* 在調整 LUN 大小之前製作快照是一個好主意。
* 如果您需要從調整 LUN 大小之前建立的快照中還原 LUN， SnapCenter會自動將 LUN 調整為快照的大小。
+
復原操作後，必須從調整大小後建立的快照中復原調整大小後新增至 LUN 的資料。



*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*磁碟*」。
. 從主機下拉清單中選擇主機。
+
磁碟已列出。

. 選擇要調整大小的磁碟，然後按一下“調整大小”。
. 在「調整磁碟大小」對話方塊中，使用滑桿工具指定磁碟的新大小，或在「大小」欄位中輸​​入新大小。
+

NOTE: 如果您手動輸入尺寸，則需要按一下「尺寸」欄位外部，然後才能正確啟用「收縮」或「擴充」按鈕。此外，您必須按一下 MB、GB 或 TB 來指定測量單位。

. 當您對輸入的內容滿意時，請根據需要按一下「*收縮*」或「*擴充*」。
+
SnapCenter調整磁碟大小。





== 連接磁碟

您可以使用連線磁碟精靈將現有 LUN 連線到主機，或重新連線已中斷連線的 LUN。

.開始之前
* 您必須已在儲存系統上啟動 FC 或 iSCSI 服務。
* 如果您正在使用 iSCSI，則必須與儲存系統建立 iSCSI 會話。
* 除非 Windows Server 故障轉移叢集中的主機共用 LUN，否則您無法將 LUN 連線至多個主機。
* 如果 LUN 由使用 CSV（叢集共用磁碟區）的 Windows Server 故障轉移叢集中的主機共用，則必須連接擁有叢集群組的主機上的磁碟。
* 只需在連接磁碟的主機上安裝適用於 Windows 的插件。


*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*磁碟*」。
. 從*主機*下拉清單中選擇主機。
. 按一下“連接”。
+
將開啟連接磁碟精靈。

. 在 LUN 名稱頁面中，確定要連接的 LUN：
+
|===
| 在這個領域... | 這樣做... 


 a| 
儲存系統
 a| 
選擇 LUN 的 SVM。



 a| 
LUN 路徑
 a| 
按一下「瀏覽」以選擇包含 LUN 的磁碟區的完整路徑。



 a| 
LUN 名稱
 a| 
輸入 LUN 的名稱。



 a| 
簇大小
 a| 
選擇叢集的 LUN 區塊分配大小。

叢集大小取決於作業系統和應用程式。



 a| 
LUN 標籤
 a| 
或者，輸入 LUN 的描述性文字。

|===
. 在磁碟類型頁面中，選擇磁碟類型：
+
|===
| 選擇... | 如果... 


 a| 
專用磁碟
 a| 
該 LUN 只能被一個主機存取。



 a| 
共享磁碟
 a| 
LUN 由 Windows Server 故障轉移叢集中的主機共用。

您只需將磁碟連接到故障轉移群集中的一台主機。



 a| 
叢集共用磁碟區 (CSV)
 a| 
此 LUN 由使用 CSV 的 Windows Server 故障轉移群集中的主機共用。

確保連接到磁碟的主機是叢集群組的擁有者。

|===
. 在磁碟機屬性頁面中，指定磁碟機屬性：
+
|===
| 財產 | 描述 


 a| 
自動分配
 a| 
讓SnapCenter根據系統磁碟機自動分配磁碟區掛載點。

例如，如果您的系統磁碟機是 C:，則自動指派屬性會在您的 C: 磁碟機下方建立磁碟區裝入點 (C:\scmnpt\)。共享磁碟不支援自動分配屬性。



 a| 
分配磁碟機號
 a| 
將磁碟安裝到您在相鄰下拉清單中選擇的磁碟機。



 a| 
使用卷掛載點
 a| 
將磁碟安裝到您在相鄰欄位中指定的磁碟機路徑。

磁碟區安裝點的根目錄必須由您正在建立磁碟的主機擁有。



 a| 
不要分配磁碟機號或磁碟區安裝點
 a| 
如果您希望在 Windows 中手動安裝磁碟，請選擇此選項。

|===
. 在映射 LUN 頁面中，選擇主機上的 iSCSI 或 FC 啟動器：
+
|===
| 在這個領域... | 這樣做... 


 a| 
主持人
 a| 
雙擊叢集群組名稱，顯示屬於該叢集的主機的下拉列表，然後選擇啟動器的主機。

只有當 LUN 由 Windows Server 故障轉移叢集中的主機共用時，才會顯示此欄位。



 a| 
選擇主機發起者
 a| 
選擇“*光纖通道*”或“*iSCSI*”，然後選擇主機上的啟動器。

如果您使用具有 MPIO 的 FC，則可以選擇多個 FC 啟動器。

|===
. 在「群組類型」頁面中，指定是否要將現有 igroup 對應到 LUN 或建立新的 igroup：
+
|===
| 選擇... | 如果... 


 a| 
為選定的啟動器建立新的 igroup
 a| 
您想要為選定的啟動器建立一個新的 igroup。



 a| 
為選定的啟動器選擇現有的 igroup 或指定新的 igroup
 a| 
您想要為選定的啟動器指定現有的 igroup，或使用您指定的名稱建立新的 igroup。

在 *igroup name* 欄位中輸入 igroup 名稱。輸入現有 igroup 名稱的前幾個字母以自動完成該欄位。

|===
. 在「摘要」頁面中，檢查您的選擇並按一下「完成」。
+
SnapCenter將 LUN 連接到主機上的指定磁碟機或磁碟機路徑。





== 斷開磁碟

您可以將 LUN 與主機斷開連接，而不會影響 LUN 的內容，但有一個例外：如果在克隆分離之前斷開連接，則會丟失克隆的內容。

.開始之前
* 確保 LUN 未被任何應用程式使用。
* 確保 LUN 未被監控軟體監控。
* 如果 LUN 是共享的，請確保從 LUN 中刪除叢集資源相依性，並驗證叢集中的所有節點是否都已開啟電源、正常運作且可供SnapCenter使用。


*關於此任務*

如果中斷SnapCenter建立的FlexClone磁碟區中的某個 LUN 且該磁碟區上沒有連接任何其他 LUN，SnapCenter會刪除該磁碟區。在斷開 LUN 之前， SnapCenter會顯示一則訊息，警告您FlexClone磁碟區可能會被刪除。

為避免自動刪除FlexClone磁碟區，您應該在斷開最後一個 LUN 之前重新命名該磁碟區。重命名卷時，請確保更改多個字符，而不僅僅是名稱中的最後一個字符。

*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*磁碟*」。
. 從*主機*下拉清單中選擇主機。
+
磁碟已列出。

. 選擇要斷開的磁碟，然後按一下“*斷開連接*”。
. 在「斷開磁碟」對話方塊中，按一下「*確定*」。
+
SnapCenter斷開磁碟連線。





== 刪除磁碟

當您不再需要磁碟時，可以將其刪除。刪除磁碟後，將無法復原。

*步驟*

. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*磁碟*」。
. 從*主機*下拉清單中選擇主機。
+
磁碟已列出。

. 選擇要刪除的磁碟，然後按一下“*刪除*”。
. 在「刪除磁碟」對話方塊中，按一下「確定」。
+
SnapCenter刪除磁碟。


