---
permalink: install/task_enable_two_way_ssl.html 
sidebar: sidebar 
keywords: security,disable two-way SSL,enable two-way SSL, windows host 
summary: 您可以啟用雙向 SSL 通信，以使用 PowerShell 命令保護 Windows 主機上的SnapCenter伺服器與插件之間的相互通訊。 
---
= 在 Windows 主機上啟用雙向 SSL 通信
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以啟用雙向 SSL 通信，以使用 PowerShell 命令保護 Windows 主機上的SnapCenter伺服器與插件之間的相互通訊。

*開始之前*

首先執行所有插件和 SMCore 代理的命令，然後執行伺服器的命令。

*步驟*

. 若要啟用雙向 SSL 通信，請在SnapCenter伺服器上執行下列命令，用於插件、伺服器以及需要雙向 SSL 通訊的每個代理程式。
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName <Plugin_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="true"}`

. 使用下列命令執行 IIS SnapCenter應用程式集區回收作業。
`> Restart-WebAppPool -Name "SnapCenter"`
. 對於 Windows 插件，透過執行下列 PowerShell 命令重新啟動 SMCore 服務：
+
`> Restart-Service -Name SnapManagerCoreService`





== 禁用雙向 SSL 通信

您可以使用 PowerShell 指令停用雙向 SSL 通訊。

*關於此任務*

* 首先執行所有插件和 SMCore 代理的命令，然後執行伺服器的命令。
* 當您停用雙向 SSL 通訊時，CA 憑證及其配置不會被刪除。
* 若要為SnapCenter Server 新增主機，必須停用所有插件主機的雙向 SSL。
* 不支援 NLB 和 F5。


*步驟*

. 若要停用雙向 SSL 通信，請在SnapCenter Server 上對所有插件主機和SnapCenter主機執行下列命令。
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName <Agent_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="false"}`

. 使用下列命令執行 IIS SnapCenter應用程式集區回收作業。
`> Restart-WebAppPool -Name "SnapCenter"`
. 對於 Windows 插件，透過執行下列 PowerShell 命令重新啟動 SMCore 服務：
+
`> Restart-Service -Name SnapManagerCoreService`


