---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: 為要備份的 Unix 檔案系統建立備份策略。 
---
= 為 Unix 檔案系統建立備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter備份 Unix 檔案系統之前，您必須為要備份的資源或資源群組建立備份原則。備份策略是一組規則，用於控制如何管理、排程和保留備份。您也可以指定複製、腳本和備份類型設定。當您想要在另一個資源或資源群組上重複使用策略時，建立策略可以節省時間。

.開始之前
* 您必須已完成安裝SnapCenter、新增主機、發現檔案系統和建立儲存系統連線等任務，為資料保護做好準備。
* 如果您要將快照複製到映像或保管庫二級存儲， SnapCenter管理員必須已為您指派來源磁碟區和目標磁碟區的 SVM。
* 查看SnapMirror主動同步特定的先決條件和限制。欲了解詳細信息，請參閱 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror主動同步的物件限制"]。


.關於此任務
* SnapLock
+
** 如果選擇了「保留備份副本特定天數」選項，則SnapLock保留期必須小於或等於上述保留天數。
+
指定快照鎖定期可防止在保留期到期之前刪除快照。這可能導致保留的快照數量超過策略中指定的數量。

+
對於ONTAP 9.12.1 及以下版本、作為復原的一部分從SnapLock Vault 快照建立的克隆將繼承SnapLock Vault 到期時間。儲存管理員應在SnapLock到期後手動清理克隆。





.步驟
. 在左側導覽窗格中，按一下「*設定*」。
. 在「設定」頁面中，按一下「*策略*」。
. 從下拉清單中選擇“*Unix 檔案系統*”。
. 點選“*新建*”。
. 在名稱頁面中，輸入策略名稱和詳細資訊。
. 在「備份和複製」頁面中，執行以下操作：
+
.. 指定備份設定。
.. 透過選擇*按需*、*每小時*、*每天*、*每週*或*每月*來指定計畫頻率。
.. 在「選擇輔助複製選項」部分中，選擇以下一個或兩個輔助複製選項：


+
|===
| 對於這個領域... | 這樣做... 


 a| 
建立本地 Snapshot 副本後更新SnapMirror
 a| 
選擇此欄位可在另一個磁碟區上建立備份集的鏡像副本（SnapMirror複製）。

應為SnapMirror主動同步啟用此選項。



 a| 
建立本機 Snapshot 副本後更新SnapVault
 a| 
選擇此選項可執行磁碟到磁碟備份複製（SnapVault備份）。



 a| 
錯誤重試次數
 a| 
輸入操作停止之前允許的最大複製嘗試次數。

|===
. 在「保留」頁面中，指定「備份和複製」頁面中所選的備份類型和計畫類型的保留設定：
+
|===


| 如果你想... | 然後... 


 a| 
保留一定數量的快照
 a| 
選擇*要保留的副本*，然後指定要保留的快照數量。

如果快照數量超過指定數量，則會刪除快照，並先刪除最舊的副本。


NOTE: 最大保留值為 1018。如果保留設定的值高於底層ONTAP版本支援的值，則備份將會失敗。


IMPORTANT: 如果您打算啟用SnapVault複製，則必須將保留計數設為 2 或更高。如果將保留計數設為 1，則保留操作可能會失敗，因為第一個快照是SnapVault關係的參考快照，直到較新的快照複製到目標。



 a| 
將快照保留一定天數
 a| 
選擇*保留副本*，然後指定在刪除快照之前要保留快照的天數。



 a| 
快照副本鎖定期
 a| 
選擇*Snapshot 副本鎖定期限*並指定天、月或年的持續時間。

Snaplock 保留期應少於 100 年。

|===
. 選擇策略標籤。
+

NOTE: 您可以為遠端複製的主快照指派SnapMirror標籤，從而允許主快照將快照複製作業從SnapCenter卸載到ONTAP二級系統。無需在策略頁面中啟用SnapMirror或SnapVault選項即可完成此操作。

. 在腳本頁面中，分別輸入要在備份作業之前或之後執行的前置腳本或後置腳本的路徑和參數。
+

NOTE: 您應該檢查這些命令是否存在於插件主機上可用的命令清單中，該清單位於 _ NetApp路徑下。

+
您也可以指定腳本超時值。預設值為 60 秒。

. 查看摘要，然後按一下「*完成*」。

