---
permalink: protect-db2/create-a-storage-system-connection-and-a-run-as-account-using-powershell-cmdlets-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: '在使用 PowerShell cmdlet 備份、還原或複製 IBM Db2 資料庫之前，必須建立儲存虛擬機器 (SVM) 連線和憑證。' 
---
= 使用 PowerShell cmdlet 為 IBM Db2 建立儲存系統連線和憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用 PowerShell cmdlet 備份、還原或複製 IBM Db2 資料庫之前，必須建立儲存虛擬機器 (SVM) 連線和憑證。

.開始之前
* 您應該已經準備好 PowerShell 環境來執行 PowerShell cmdlet。
* 您應該擁有基礎設施管理員角色所需的權限來建立儲存連線。
* 您應該確保插件安裝沒有正在進行中。
+
新增儲存系統連線時，不得進行主機外掛程式安裝，因為主機快取可能不會更新，且資料庫狀態可能會在SnapCenter GUI 中顯示為「不可用於備份」或「不在NetApp儲存上」。

* 儲存系統名稱應該是唯一的。
+
SnapCenter不支援不同叢集上具有相同名稱的多個儲存系統。  SnapCenter支援的每個儲存系統都應具有唯一的名稱和唯一的資料 LIF IP 位址。



.步驟
. 點選 *SnapCenterPS* 啟動 PowerShell Core。
. 使用 Add-SmStorageConnection cmdlet 建立與儲存系統的新連線。
+
[listing]
----
PS C:\> Add-SmStorageConnection -StorageType DataOntap -Type DataOntap -OntapStorage ‘scsnfssvm’ -Protocol Https -Timeout 60
----
. 使用 Add-SmCre​​dential cmdlet 建立新憑證。
+
此範例顯示如何使用 Windows 憑證建立名為 FinanceAdmin 的新憑證：

+
[listing]
----
PS C:\> Add-SmCredential -Name 'FinanceAdmin' -Type Linux -AuthenticationType PasswordBased -Credential db2hostuser -EnableSudoPrevileges:$true
----
. 將 IBM Db2 通訊主機新增至SnapCenter Server。
+
對於 Linux：

+
[listing]
----
PS C:\> Add-SmHost -HostType Linux -HostName '10.232.204.61' -CredentialName 'defaultcreds'
----
+
對於 Windows：

+
[listing]
----
PS C:\> Add-SmHost -HostType Windows -HostName '10.232.204.61' -CredentialName 'defaultcreds'
----
. 在主機上安裝軟體套件和適用於 IBM Db2 的SnapCenter插件。
+
對於 Linux：

+
[listing]
----
PS C:\> Install-SmHostPackage -HostNames '10.232.204.61' -PluginCodes DB2
----
+
對於 Windows：

+
[listing]
----
PS C:\> Install-SmHostPackage -HostNames '10.232.204.61' -PluginCodes DB2,SCW
----
. 設定 SQLLIB 的路徑。
+
對於 Windows，Db2 外掛程式將使用 SQLLIB 資料夾的預設路徑：“C:\Program Files\IBM\SQLLIB\BIN”

+
如果要覆蓋預設路徑，請使用下列命令。

+
[listing]
----
PS C:\> Set-SmConfigSettings -Plugin -HostName '10.232.204.61' -PluginCode DB2 -configSettings @{"DB2_SQLLIB_CMD"="<custom_path>\IBM\SQLLIB\BIN"}

----


可以透過執行_Get-Help command_name_來取得有關可與 cmdlet 一起使用的參數及其描述的資訊。或者，您也可以參考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter軟體 Cmdlet 參考指南"^]。
