---
permalink: protect-db2/create-backup-policies-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 在使用SnapCenter備份 IBM Db2 資料庫資源之前，您必須為要備份的資源或資源群組建立備份原則。備份策略是一組規則，用於控制如何管理、排程和保留備份。 
---
= 為 IBM Db2 建立備份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter備份 IBM Db2 資源之前，您必須為要備份的資源或資源群組建立備份原則。備份策略是一組規則，用於控制如何管理、排程和保留備份。

.開始之前
* 您必須已經定義了您的備份策略。
+
有關詳細信息，請參閱有關為 IBM Db2 資料庫定義資料保護策略的資訊。

* 您必須已完成安裝SnapCenter、新增主機、設定儲存系統連線和新增資源等任務，為資料保護做好準備。
* 如果您要將快照複製到映像或保管庫， SnapCenter管理員必須已為您指派來源磁碟區和目標磁碟區的 SVM。
+
此外，您還可以在策略中指定複製、腳本和應用程式設定。當您想要將該策略重新用於另一個資源群組時，這些選項可以節省時間。



.關於此任務
* SnapLock
+
** 如果選擇了「保留備份副本特定天數」選項，則SnapLock保留期必須小於或等於上述保留天數。
** 指定快照鎖定期可防止在保留期到期之前刪除快照。這可能會導致保留的快照數量超過策略中指定的數量。
** 對於ONTAP 9.12.1 及以下版本、作為復原的一部分從SnapLock Vault 快照建立的克隆將繼承SnapLock Vault 到期時間。儲存管理員應在SnapLock到期後手動清理克隆。




.步驟
. 在左側導覽窗格中，按一下「*設定*」。
. 在「設定」頁面中，按一下「*策略*」。
. 點選“*新建*”。
. 在名稱頁面中，輸入策略名稱和詳細資訊。
. 在「策略類型」頁面中，執行以下操作：
+
.. 選擇儲存類型。
.. 在*自訂備份設定*部分，提供任何必須以鍵值格式傳遞給外掛程式的特定備份設定。
+
您可以提供多個鍵值傳遞給插件。



. 在「快照和複製」頁面中，執行下列操作。
+
.. 透過選擇*按需*、*每小時*、*每天*、*每週*或*每月*來指定計畫頻率。
+

NOTE: 您可以在建立資源組時指定備份作業的計畫（開始日期、結束日期和頻率）。這使您能夠建立共享相同策略和備份頻率的資源群組，還使您能夠為每個策略分配不同的備份計劃。

+

NOTE: 如果您已安排在凌晨 2:00，則夏令時 (DST) 期間不會觸發該計劃。

.. 在快照設定部分中，執行以下操作：
+
|===
| 如果你想... | 然後... 


 a| 
保留一定數量的快照
 a| 
選擇*要保留的副本*，然後指定要保留的快照數量。

如果快照數量超過指定數量，則會刪除快照，並先刪除最舊的副本。



 a| 
將快照保留一定天數
 a| 
選擇*保留副本*，然後指定在刪除快照之前要保留快照的天數。



 a| 
快照副本鎖定期
 a| 
選擇*Snapshot 副本鎖定期限*並指定天、月或年。

Snaplock 保留期應少於 100 年。

|===
+

IMPORTANT: 對於基於 Snapshot 副本的備份，如果您打算啟用SnapVault複製，則必須將保留計數設為 2 或更高。如果將保留計數設為 1，則保留操作可能會失敗，因為第一個快照是SnapVault關係的參考快照，直到較新的快照複製到目標。

.. 指定策略標籤。
+
您可以為遠端複製的主快照指派SnapMirror標籤，從而允許主快照將快照複製作業從SnapCenter卸載到ONTAP二級系統。無需在策略頁面中啟用SnapMirror或SnapVault選項即可完成此操作。



. 在「選擇輔助複製選項」部分中，選擇以下一個或兩個輔助複製選項：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
建立本地 Snapshot 副本後更新SnapMirror
 a| 
選擇此欄位可在另一個磁碟區上建立備份集的鏡像副本（SnapMirror複製）。

應為SnapMirror主動同步啟用此選項。



 a| 
建立本機 Snapshot 副本後更新SnapVault
 a| 
選擇此選項可執行磁碟到磁碟備份複製（SnapVault備份）。



 a| 
錯誤重試次數
 a| 
輸入操作停止之前允許的最大複製嘗試次數。

|===
+

NOTE: 您應該在ONTAP中為二級儲存配置SnapMirror保留策略，以避免達到二級儲存上快照的最大限制。

. 查看摘要，然後按一下「*完成*」。

