---
permalink: protect-nsp/set_up_credentials_for_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter使用憑證對SnapCenter操作的使用者進行身份驗證。您應該建立用於安裝SnapCenter插件的憑證以及用於在資料庫或 Windows 檔案系統上執行資料保護作業的附加憑證。 
---
= 為NetApp支援的插件設定憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter使用憑證對SnapCenter操作的使用者進行身份驗證。您應該建立用於安裝SnapCenter插件的憑證以及用於在資料庫或 Windows 檔案系統上執行資料保護作業的附加憑證。

.開始之前
* Linux 或 AIX 主機
+
您必須設定在 Linux 或 AIX 主機上安裝插件的憑證。

+
您必須為 root 使用者或具有 sudo 權限的非 root 使用者設定憑證才能安裝和啟動插件進程。

+
|===


| *最佳實務：*雖然您可以在部署主機和安裝外掛程式後為 Linux 建立憑證，但最佳實務是在新增 SVM 之後、部署主機和安裝外掛程式之前建立憑證。 
|===
* Windows 主機
+
在安裝插件之前，您必須設定 Windows 憑證。

+
您必須設定具有管理員權限的憑證，包括遠端主機上的管理員權限。

* NetApp支援的插件應用程式
+
該插件使用在新增資源時選擇或建立的憑證。如果資源在資料保護作業期間不需要憑證，則可以將憑證設定為*無*。



.關於此任務
如果您為單一資源群組設定憑證，且使用者名稱沒有完全管理權限，則必須至少為該使用者名稱指派資源群組和備份權限。

.步驟
. 在左側導覽窗格中，按一下「*設定*」。
. 在「設定」頁面中，按一下「*憑證*」。
. 點選“*新建*”。
. 在「*憑證*」頁面中，指定配置憑證所需的資訊：
+
|===
| 對於這個領域... | 這樣做... 


 a| 
憑證名稱
 a| 
輸入憑證的名稱。



 a| 
使用者名稱
 a| 
輸入用於身份驗證的使用者名稱和密碼。

** 網域管理員或管理員群組的任何成員
+
指定要安裝SnapCenter插件的系統上的網域管理員或管理員群組的任何成員。用戶名字段的有效格式為：

+
*** _NetBIOS\使用者名稱_
*** _域 FQDN\用戶名_


** 本機管理員（僅適用於工作群組）
+
對於屬於工作群組的系統，請在要安裝SnapCenter插件的系統上指定內建的本機管理員。如果使用者帳戶具有提升的權限或主機系統上停用了使用者存取控制功能，則可以指定屬於本機管理員群組的本機使用者帳戶。使用者名字段的有效格式為：_UserName_





 a| 
密碼
 a| 
輸入用於身份驗證的密碼。



 a| 
身份驗證類型
 a| 
選擇您想要使用的身份驗證類型。



 a| 
使用 sudo 權限
 a| 
如果您要為非 root 使用者建立憑證，請勾選「*使用 sudo 權限*」複選框。


NOTE: 僅適用於 Linux 和 AIX 使用者。

|===
. 按一下“*確定*”。


完成憑證設定後，您可能想要在「使用者和造訪」頁面上將憑證維護指派給使用者或使用者群組。
