---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: 憑證根據應用程式或環境使用不同的身份驗證方法。憑證對使用者進行身份驗證，以便他們可以執行SnapCenter操作。您應該建立一組用於安裝插件的憑證和另一組用於資料保護操作的憑證。 
---
= SnapCenter憑證的驗證方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
憑證根據應用程式或環境使用不同的身份驗證方法。憑證對使用者進行身份驗證，以便他們可以執行SnapCenter操作。您應該建立一組用於安裝插件的憑證，並建立另一組用於資料保護操作的憑證。



== Windows 驗證

Windows 驗證方法針對 Active Directory 進行驗證。對於 Windows 身份驗證，Active Directory 是在SnapCenter之外設定的。 SnapCenter無需額外配置即可進行身份驗證。您需要 Windows 憑證來新增主機、安裝插件包和排程作業。



== 不受信任的網域身份驗證

SnapCenter允許屬於不受信任網域的使用者和群組建立 Windows 憑證。為了讓身分驗證成功，您應該向SnapCenter註冊不受信任的網域。



== 本機工作群組身份驗證

SnapCenter允許使用本機工作群組使用者和群組建立 Windows 憑證。本機工作群組使用者和群組的 Windows 驗證不會在 Windows 憑證建立期間發生，而是會延遲到主機註冊和其他主機操作執行時發生。



== SQL Server 驗證

SQL 驗證方法針對 SQL Server 執行個體進行驗證。這意味著必須在SnapCenter中發現 SQL Server 執行個體。因此，在新增SQL憑證前，必須先新增主機、安裝外掛程式包、刷新資源。您需要 SQL Server 驗證才能執行 SQL Server 上的排程或發現資源等操作。



== Linux 驗證

Linux 驗證方法針對 Linux 主機進行驗證。在從SnapCenter GUI 遠端新增 Linux 主機和安裝適用於 Linux 的SnapCenter插件套件的初步步驟中，您需要進行 Linux 驗證。



== AIX 身份驗證

AIX 驗證方法針對 AIX 主機進行驗證。在從SnapCenter GUI 遠端新增 AIX 主機和安裝 AIX的 SnapCenter插件包的初步步驟中，您需要進行 AIX 驗證。



== Oracle 資料庫驗證

Oracle 資料庫驗證方法針對 Oracle 資料庫進行驗證。如果資料庫主機上停用了作業系統 (OS) 驗證，則需要 Oracle 資料庫驗證才能在 Oracle 資料庫上執行操作。因此，在新增 Oracle 資料庫憑證之前，您應該在 Oracle 資料庫中建立具有 sysdba 權限的 Oracle 使用者。



== Oracle ASM 身份驗證

Oracle ASM 驗證方法針對 Oracle 自動儲存管理 (ASM) 執行個體進行驗證。如果您需要存取 Oracle ASM 執行個體且資料庫主機上停用了 OS 驗證，則需要進行 Oracle ASM 驗證。在新增 Oracle ASM 憑證之前，請在 ASM 實例中建立具有系統權限的 Oracle 使用者。



== RMAN 目錄驗證

RMAN 目錄驗證方法針對 Oracle Recovery Manager (RMAN) 目錄資料庫進行驗證。如果您已經設定了外部目錄機制並將您的資料庫註冊到目錄資料庫，則需要新增 RMAN 目錄驗證。
