---
permalink: get-started/concept_disaster_recovery.html 
sidebar: sidebar 
keywords: Disaster Recovery, DR, crash, resource deleted 
summary: 當發生資源損壞或伺服器崩潰等災難時，您可以使用SnapCenter災難復原功能恢復SnapCenter伺服器。 
---
= SnapCenter中的災難復原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter災難復原 (DR) 功能可讓您從資源損壞或伺服器崩潰等災難中復原。它有助於恢復SnapCenter儲存庫、伺服器計劃、配置元件以及 SQL Server 的SnapCenter插件及其儲存。

本節介紹SnapCenter中的兩種 DR 類型：



== SnapCenter伺服器災難復原

* SnapCenter Server 資料已備份，無需在SnapCenter Server 上新增或管理任何外掛程式即可復原。
* 輔助SnapCenter伺服器應安裝在與主SnapCenter伺服器相同的安裝目錄和連接埠上。
* 對於多重驗證 (MFA)，在SnapCenter Server DR 期間，關閉所有瀏覽器標籤並重新開啟瀏覽器以再次登入。這將清除現有或活動的會話 cookie 並更新正確的設定資料。
* SnapCenter災難復原功能使用 REST API 來備份SnapCenter伺服器。看link:../tech-refresh/task_tech_refresh_server_host.html["用於SnapCenter Server 災難復原的 REST API 工作流程"] 。
* 審計設定相關的設定檔未在 DR 備份中備份，還原作業後也不會在 DR 伺服器上備份。您應該手動重複審計日誌設定。




== SnapCenter插件與儲存災難復原

DR 僅適用於 SQL Server 的SnapCenter插件。如果外掛程式關閉，請切換到另一個 SQL 主機並按照以下步驟還原資料。看link:../protect-scsql/task_disaster_recovery_scsql.html["SnapCenter插件 for SQL Server 的災難復原"] 。

SnapCenter使用ONTAP SnapMirror複製數據，透過將數據同步到輔助站點，可以用於 DR。若要啟動故障轉移，請中斷SnapMirror複製。在回退期間，逆轉同步以將資料從 DR 站點複製回主位置。
