---
permalink: get-started/concept_resources_resource_groups_and_policies.html 
sidebar: sidebar 
keywords: resource, resource group, policy 
summary: 在使用SnapCenter之前，了解與要執行的備份、複製和還原作業相關的基本概念會很有幫助。 
---
= 資料保護的關鍵概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter之前，請先了解備份、複製和還原的關鍵概念。



== 資源

資源包括資料庫、Windows 檔案系統或使用SnapCenter備份或複製的檔案共用。根據您的環境，資源也可能是資料庫執行個體、SQL Server 可用性群組、Oracle 資料庫、RAC 資料庫或自訂應用程式群組。



== 資源組

資源組是主機或叢集上的資源集合，可能來自多個主機和叢集。對資源組執行的操作將根據指定的計劃應用於其所有資源。您可以對單一資源或群組執行按需或排程備份。


NOTE: 如果共用資源組中的一個主機進入維護模式，則該組的所有主機上的所有排程操作都會暫停。

使用相關外掛程式來備份特定資源：資料庫外掛程式用於資料庫，檔案系統外掛程式用於檔案系統，以及SnapCenter Plug-in for VMware vSphere用於虛擬機器和資料儲存區。



== 政策

策略指定備份頻率、副本保留、複製、腳本和資料保護作業的其他特徵。

建立資源群組或執行按需備份時可以選擇一個或多個策略。

資源組定義需要保護的內容以及何時（以日期和時間為單位）進行保護。政策描述如何實施保護。例如，如果需要備份主機的所有資料庫或檔案系統，則可以建立包含主機中所有資料庫或檔案系統的資源群組。然後可以將兩個策略附加到資源群組：每日策略和每小時策略。

建立資源群組並附加原則時，可以將其配置為每天執行一次完整備份，並每小時執行一次日誌備份的另一個計畫。

自訂處方和附言可用於資料保護操作。這些腳本允許在資料保護作業之前或之後自動化。例如，腳本可以自動通知資料保護作業失敗或警告。在製定前言和後記之前，了解創建這些腳本的要求至關重要。



== 前言和後記的使用

自訂的處方和後記可以在作業之前或之後自動執行資料保護任務。例如，您可以新增一個腳本來通知您作業失敗或警告。在設定它們之前，請確保您了解這些腳本的要求。



=== 支援的腳本類型

Windows 支援以下類型的腳本：

* 批次檔
* PowerShell 腳本
* Perl 腳本


UNIX 支援以下類型的腳本：

* Perl 腳本
* Python 腳本
* Shell 腳本
+

NOTE: 除了預設的 bash shell 之外，還支援其他 shell，如 sh-shell、k-shell 和 c-shell。





=== 腳本路徑

作為非虛擬化和虛擬化儲存系統上的SnapCenter操作的一部分運行的所有前腳本和後腳本都在插件主機上執行。

* Windows 腳本應位於插件主機上。



NOTE: 前言或後記路徑不應包含磁碟機或共用。該路徑應相對於 SCRIPTS_PATH。

* UNIX 腳本應位於插件主機上。



NOTE: 腳本路徑在執行時進行驗證。



=== 在哪裡指定腳本

腳本在備份策略中指定。當備份作業開始時，策略會自動將腳本與正在備份的資源關聯起來。建立備份策略時，您可以指定前言和後記參數。


NOTE: 您不能指定多個腳本。



=== 腳本逾時

預設情況下，超時設定為 60 秒。您可以修改超時值。



=== 腳本輸出

Windows 腳本和後記輸出檔案的預設目錄是 Windows\System32。

UNIX 前言和後記沒有預設位置。您可以將輸出檔案重新導向到任何首選位置。
