---
permalink: uninstall/task_uninstall_plug_ins_from_a_host_using_the_snapcenter_gui.html 
sidebar: sidebar 
keywords: uninstall, gui 
summary: 當您決定不再需要單一插件或插件包時，您可以使用SnapCenter介面將其卸載。 
---
= 使用SnapCenter GUI 卸載插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您決定不再需要單一插件或插件包時，您可以使用SnapCenter介面將其卸載。

.開始之前
* 您應該已經刪除了正在卸載的插件包的資源組。
* 您應該已經分離了與要卸載的插件包的資源組關聯的策略。


.關於此任務
您可以卸載單一插件。例如，您可能需要卸載適用於 Microsoft SQL Server 的SnapCenter插件，因為主機資源不足，而您想將該插件移至功能更強大的主機。您也可以卸載整個插件包。例如，您可能需要卸載適用於 Linux 的SnapCenter插件包，其中包括適用於 Oracle 資料庫的SnapCenter插件和適用於 UNIX 的SnapCenter插件。

* 刪除主機包括卸載所有插件。
+
從SnapCenter中刪除主機時， SnapCenter會在刪除主機之前卸載主機上的所有插件包。

* SnapCenter GUI 一次從一個主機中刪除插件。
+
使用SnapCenter GUI 時，您一次只能卸載一台主機上的插件。但是，您可以同時執行多個卸載操作。

+
您也可以使用 _Uninstall-SmHostPackage_ cmdlet 和所需參數從多個主機卸載插件。可以透過執行_Get-Help command_name_來取得有關可與 cmdlet 一起使用的參數及其描述的資訊。或者，您也可以參考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter軟體 Cmdlet 參考指南"^]。




IMPORTANT: 從安裝了SnapCenter伺服器的主機上解除安裝適用於 Windows 的SnapCenter插件包將損壞SnapCenter伺服器安裝。除非您確定不再需要SnapCenter伺服器，否則請勿解除安裝適用於 Windows 的SnapCenter插件套件。

.步驟
. 在左側導覽窗格中，按一下「*主機*」。
. 在「主機」頁面中，按一下「*託管主機*」。
. 在「受管主機」頁面中，選擇要從中解除安裝外掛程式或外掛程式套件的主機。
. 在您想要刪除的插件旁邊，點擊*刪除*>*提交*。


.完成後
您應該等待 5 分鐘，然後再在該主機上重新安裝插件。此時段足以讓SnapCenter GUI 刷新託管主機的狀態。如果立即重新安裝該插件，安裝將會失敗。

如果您要卸載適用於 Linux 的SnapCenter插件包，則可以在下列位置找到卸載特定的日誌檔案：_/custom_location/snapcenter/log_。
