---
permalink: protect-mysql/create-a-storage-system-connection-and-a-run-as-account-using-powershell-cmdlets-for-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: '在使用 PowerShell cmdlet 備份、還原或複製 MySQL 資料庫之前，必須建立儲存虛擬機器 (SVM) 連線和憑證。' 
---
= 使用 PowerShell cmdlet 為 MySQL 建立儲存系統連線和憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用 PowerShell cmdlet 備份、還原或複製 MySQL 資料庫之前，必須建立儲存虛擬機器 (SVM) 連線和憑證。

.開始之前
* 您應該已經準備好 PowerShell 環境來執行 PowerShell cmdlet。
* 您應該擁有基礎設施管理員角色所需的權限來建立儲存連線。
* 您應該確保插件安裝沒有正在進行中。
+
新增儲存系統連線時，不得進行主機外掛程式安裝，因為主機快取可能不會更新，且資料庫狀態可能會在SnapCenter GUI 中顯示為「不可用於備份」或「不在NetApp儲存上」。

* 儲存系統名稱應該是唯一的。
+
SnapCenter不支援不同叢集上具有相同名稱的多個儲存系統。  SnapCenter支援的每個儲存系統都應具有唯一的名稱和唯一的資料 LIF IP 位址。



.步驟
. 使用 Open-SmConnection cmdlet 啟動 PowerShell Core 連線會話。
+
[listing]
----
PS C:\> Open-SmConnection
----
. 使用 Add-SmStorageConnection cmdlet 建立與儲存系統的新連線。
+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. 使用 Add-SmCre​​dential cmdlet 建立新憑證。
+
此範例顯示如何使用 Windows 憑證建立名為 FinanceAdmin 的新憑證：

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----
. 將 MySQL 通訊主機新增至SnapCenter Server。
+
[listing]
----
PS C:> Add-SmHost -HostName 10.232.204.61 -OSType Windows -RunAsName FinanceAdmin -PluginCode mysql
----
. 在主機上安裝軟體套件和適用於 MySQL 的SnapCenter插件。
+
對於 Linux：

+
[listing]
----
PS C:> Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode mysql
----
+
對於 Windows：

+
[listing]
----
Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode mysql -FilesystemCode scw -RunAsName FinanceAdmin
----
. 設定 SQLLIB 的路徑。
+
對於 Windows，MySQL 外掛程式將使用 SQLLIB 資料夾的預設路徑：“C:\Program Files\IBM\SQLLIB\BIN”

+
如果要覆蓋預設路徑，請使用下列命令。

+
[listing]
----
PS C:> Set-SmConfigSettings -Plugin -HostName 10.232.204.61 -PluginCode
MySQL -configSettings @{“MySQL_SQLLIB_CMD” = “<custom_path>\IBM\SQLLIB\BIN”}

----


可以透過執行_Get-Help command_name_來取得有關可與 cmdlet 一起使用的參數及其描述的資訊。或者，您也可以參考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter軟體 Cmdlet 參考指南"^]。
